package com.fa.cim.common.constant;

/**
 * description:
 * This file use to define transaction ID by Enum
 * change history:
 * date             defect#             person             comments
 * ---------------------------------------------------------------------------------------------------------------------
 * 2018/3/20        ********            Bear         create file
 *
 * @author: Bear
 * @date: 2018/3/20 10:18
 * @copyright: 2018, FA Software (Shanghai) Co., Ltd. All Rights Reserved.
 */
public enum TransactionIDEnum {
    NULL(null),

    TXBOC006("TXBOC006"),
    TXBOC009("TXBOC009"),

    AUTO_FLOW_BATCHING_REQ("OFLWW002"),
    BANK_LIST_INQ("OBNKQ001"),
    Qrest_Time_Candidate_Inq("OPRCQ003"),
    QREST_TIME_ACTION_EXEC_REQ("OPRCW004"),
    EXPIRED_QREST_TIME_LOT_LIST_INQ("OPRCQ006"),
    CASSETTE_LIST_INQ("ODRBQ002"),      // CarrierListInq ID
    CASSETTE_DELIVERY_REQ("OTMSW001"),  // The CarrierTransferReq ID
    CASSETTE_DELIVERY_FOR_INTERNAL_BUFFER_REQ("OTMSW002"), // The TxCarrierTransferForIBReq ID
    FMC_CASSETTE_DELIVERY_REQ("TXDSC017"), // The TxSLMCassetteDeliveryReq ID
    DMS_DELIVERY_REQ("OTMSW015"),
    DMS_DELIVERY_REQ_FOR_INTERNAL_BUFFER_REQ("OTMSW016"),

    CASSETTE_STATUS_INQ("ODRBQ001"),    //CarrierDetailInfoInq
    CASSETTE_OUT_FROM_INTERNAL_BUFFER_REQ("OEQPW022"),  //The CarrierOutFromIBReq ID

    QTIME_ACTION_RESET_BY_POST_PROC_REQ("OPRCW011"),
    FUTURE_REWORK_CANCEL_REQ("OPRCW010"),

    CONTROL_JOB_MANAGE_REQ("OCJPW001"),
    CODE_LIST_INQ("OSYSQ002"),                       // The CodeSelectionInq Transaction ID
    CHAMBER_STATUS_CHANGE_REQ("OEQPW011"),         // ChamberStatusChangeReq ID
    CHAMBER_STATUS_CHANGE_RPT("OEQPR007"),        // ChamberStatusChangeRpt ID

    CHANGE_WAFER_SORTER_ACTION_REQ("OSRTW003"), // The TxWaferSorterActionRegisterReq ID

    //reticle action
    RETICLE_CONFIRM_MASK_QUALITY("ORTLW001"),
    RETICLE_INSPECTION_REQUEST("ORTLW002"),
    RETICLE_INSPECTION_IN("ORTLW003"),
    RETICLE_INSPECTION_OUT("ORTLW004"),
    RETICLE_HOLD("ORTLW005"),
    RETICLE_HOLD_RELEASE("ORTLW006"),
    RETICLE_TERMINATE("ORTLW007"),
    RETICLE_TERMINATE_CANCEL("ORTLW008"),
    RETICLE_REQUEST_REPAIR("ORTLW009"),
    RETICLE_REPAIR_IN("ORTLW010"),
    RETICLE_REPAIR_OUT("ORTLW011"),
    RETICLE_SCRAP("ORTLW012"),
    RETICLE_SCRAP_CANCEL("ORTLW013"),
    RETICLE_SCAN_REQUEST("ORTLW014"),
    RETICLE_SCAN_COMPLETE("ORTLW015"),
    RETICLE_INSPECTION_TYPE_CHANGE("ORTLW016"),
    HOLD_RETICLE_LIST("ORTLQ101"),
    RETICLE_UPDATE_PARAMS_INQ("ORTLQ102"),

    DURABLE_REGIST_REQ("ODRBW001"),                     //DurableSetReq ID
    DURABLE_BANK_IN_REQ("ODRBW020"),                   //TxDurableBankInReq ID
    DURABLE_BANK_IN_CANCEL_REQ("ODRBW019"),                   //TxDurableBankInReq ID
    DURABLE_BANK_DELETE_REQ("ODRBW023"),                   //TxDurableDeleteReq ID
    DURABLE_BANK_MOVE_REQ("ODRBW021"),                   //TxdurableBankMoveReq ID
    DURABLE_GATE_PASS_REQ("ODRBW025"),                   //TxDurableGatePassReq ID
    DURABLE_OPE_LOCATE_REQ("ODRBW027"),                   //durableOpeLocateReq ID
    DURABLE_PROCESS_LAG_TIME_UPDATE("ODRBW033"),//TxDurableProcessLagTimeUpdateReq
    DURABLE_CONTROL_JOB_MANAGE_REQ("ODRBW022"),//TxDurableControlJobManageReq

    ENV_VARIABLE_INFO_INQ("OSYSQ001"),   // The TxOMSEnvInfoInq ID
    ENV_VARIABLE_UPDATE_REQ("OSYSW001"),   // The TxOMSEnvModifyReq ID

    USER_DEFINED_ATTRIBUTE_INFO_INQ("OCDAQ002"), // The TxUserDefinedAttributeInfoInq ID

    EQP_FLOW_BATCH_MAX_COUNT_CHANGE_REQ("OFLWW008"),   // EqpMaxFlowbCountModifyReq ID
    /**
     * The EqpBufferTypeModifyReq Transaction ID
     */
    EQP_BUFFER_RRESOURCE_TYPE_CHANGE_REQ("OEQPW019"),
    CANDIDATE_EQUIPMENT_INQ("OEQPQ009"),
    EQP_INFO_FOR_INTERNAL_BUFFER_INQ("OEQPQ002"),   // EqpInfoForIBInq ID
    EQP_NOTE_INQ("OEQPQ013"),                       //EqpMemoInfoInq ID
    EQP_MODE_CHANGE_REQ("OEQPW002"),                // EqpModeChangeReq ID
    EQP_NOTE_REGIST_REQ("OEQPW018"),                // EqpNoteResigtReq ID
    EQP_STATUS_ADJUST_REQ("OEQPW017"),                // EqpEAPStatusSyncReq ID
    EQP_RESERVE_REQ("OFLWW003"),                    // EqpReserveForFlowBatchReq ID
    EQP_RESERVE_CANCEL_REQ("OFLWW004"),             // EqpReserveCancelForflowBatchReq ID
    EQP_RELATED_RECIPELID_LIST_INQ("OEQPQ014"),   //EqpRelatedRecipel ID
    EQP_LIST_INQ("OEQPQ003"),             // EqpReserveCancelForflowBatchReq ID
    EQP_LIST_BY_OPERATION_INQ("OEQPQ004"),             // EqpListByStepInq ID
    EQP_STATUS_CHANGE_REQ("OEQPW001"),              // The EqpStatusChangeReq ID
    EQP_STATUS_RECOVER_REQ("OEQPW015"),              // The EqpStatusResetReq ID
    EQP_LOT_CASSETTE_XFER_STATUS_CHANGE_RPT("OTMSR001"),              // The EqpCarrierTransferStatusChangeRpt ID
    EQP_STATUS_CHANGE_RPT("OEQPR003"),              // The EqpStatusChangeRpt ID
    /**
     * The WaferPositionWithProcessResourceRpt Transaction ID
     */
    PROCESS_RESOURCE_WAFER_POSITION_RPT("OEQPR011"),
    CARRIER_OUT_FROM_IB_REQ("OEQPW022"),
    EQP_DETAIL_INFO_INQ("OEQPQ011"),             // EqpEAPInfoInq ID
    EQP_ID_LIST_INQ("OEQPQ016"),                // EqpIDListInq ID
    EQP_AUTO_3SETTING_LIST_INQ("ODISQ007"),                // EqpFullAutoConfigListInq ID
    WHAT_NEXT_DURABLE_LIST_INQ("ODRBQ032"),                // whatNextDurableListInq ID
    EQP_AUTO_3SETTING_UPDATE_REQ("ODISW008"),              // EqpFullAutoConfigChgReq ID
    EQP_PORT_STATUS_CHANGE_RPT("OEQPR004"),     //PortStatusChangeRpt ID
    WORK_AREA_LIST_INQ("OEQPQ017"),             // BayListInq ID
    COLLECTED_DATA_ACTION_INQ("OEDCQ005"),             // EDCSpecCheckActionResultInq ID
    DATA_SPEC_CHECK_RESULT_INQ("OEDCQ004"),             // specCheckResultInq ID
    COLLECTED_DATA_ACTION_BY_PJ_REQ("OEDCW005"),             // The TxEDCWithSpecCheckActionByPJReq ID
    EDCWITH_SPEC_CHECK_ACTION_BY_POST_TASK_REQ("OEDCW006"),             // The EDCWithSpecCheckActionByPostTaskReq ID
    CANDIDATE_DURABLE_STATUS_INQ("ODRBQ004"),             // DurableStatusSelectionInq ID
    IB_FURNACE_EQP_BATCH_INFO("OEQPQ018"),             // BayListInq ID
    /**
     * ReticlePodDetailInfoInq__170 ID
     */
    RETICLE_POD_STATUS_QIN("ODRBQ008"),
    /**
     * ReticlePodListInq__170 ID
     */
    RETICLE_POD_LIST_INQ("ODRBQ009"),
    CASSETTE_BASE_INFO_LIST_INQ("ODRBQ003"),             // CarrierBasicInfoInq ID
    CASSETTE_STATUS_MULTI_CHANGE_RPT("ODRBR002"),             // MultipleCarrierStatusChangeRpt ID
    /**
     * ReticlePodTransferStatusChangeRpt__160 ID
     */
    RETICLE_POD_XFER_STAUES_CHANGE_RPT("ODRBR008"),
    CASSETTE_USAGE_COUNT_RESET_REQ("ODRBW002"),             // CarrierUsageCountResetReq ID
    CASSETTE_DISPATCH_ATTRIBUTE_UPDATE_REQ("ODISW006"),             // CarrierDispatchAttrChgReq ID
    RETICLE_POD_INVENTORY_RPT("ODRBR016"),             // cxReticlePodInvUpdateRpt__090
    RETICLE_JUST_IN_OUT_RPT("ODRBR003"),                    //ReticleAllInOutRpt ID
    OPE_GUIDE_INFO_INQ("OINFQ008"),                  //OpeGuidInfoInq ID
    DC_DEF_DETAIL_INFO_INQ("OEDCQ002"),             // EDCPlanInfoInq ID
    DC_SPEC_DETAIL_INFO_INQ("OEDCQ003"),             // EDCSpecInfoInq ID
    RETICLE_LIST_INQ("ODRBQ007"),             // ReticleListInq__170 ID
    RETICLE_STATUS_CHANGE_RPT("ODRBR004"),             // ReticleStatusChangeRpt ID
    RETICLE_STATUS_INQ("ODRBQ006"),             // ReticleDetailInfoInq__170 ID
    RETICLE_STATUS_MULTI_CHANGE_RPT("ODRBR007"),             // MultipleReticleStatusChangeRpt ID
    RETICLE_USAGE_COUNT_RESET_REQ("ODRBW006"),             // ReticleUsageCountResetReq ID
    RETICLE_XFER_STATUS_CHANGE_RPT("ODRBR005"),             // ReticleTransferStatusChangeRpt__160 ID
    RECIPE_PARAMETER_ADJUST_REQ("ORCPW006"),
    RECIPE_PARAMETER_ADJUST_IN_PROCESSING_REQ("ORCPW007"),
    CASSETTE_STATUS_CHANGE_RPT("ODRBR001"),             // CarrierStatusChangeRpt ID
    CHAMBER_PROCESS_WAFER_RPT("OEQPR010"),                      //ChamberWithProcessWaferRpt ID
    STOCKER_INFO_INQ("OTMSQ001"),             // StockerInfoInq ID
    STOCKER_LIST_INQ("OTMSQ002"),             // StockerListInq ID
    WHERE_NEXT_UTS_CARRIER_INQ("OTMSQ009"),             // TxWhereNextOHBCarrierInq
    STOCKER_INVENTORY_RPT("OTMSR004"),             //StockerInventoryRpt ID
    STOCKER_STATUS_CHANGE_RPT("OTMSR005"),          //StockerStatusChangeRpt id
    STOCKER_INVENTORY_REQ("OTMSW011"),        //StockerInventoryUploadReq ID
    AVAILABLE_STOCKER_INQ("OTMSQ006"),             // StockerForAutoTransferInq ID
    AVAILABLE_EQP_INQ("OTMSQ007"),             // EqpForAutoTransferInq ID
    ALL_AVAILABLE_EQP_INQ("OTMSQ008"),             // AllEqpForAutoTransferInq ID
    EQP_USAGE_COUNT_RESET_REQ("OEQPW016"),          // The EqpUsageCountResetReq ID
    FLOW_BATCHING_REQ("OFLWW001"),                   // The FlowBatchByManualActionReq ID
    FORCE_OPERATION_COMP_REQ("OEQPW014"),                 // The ForceOpenCompReq ID
    FORCE_OPERATION_COMP_FOR_INTERNAL_BUFFER_REQ("OEQPW023"),        // The ForceMoveOutForIBReq ID
    LOT_LIST_INQ("OLOTQ002"),                        // The LotListInq Transaction ID
    LOT_REMOVE_FROM_FLOW_BATCH_REQ("OFLWW005"),    // The FlowBatchLotRemoveReq ID
    FLOW_BATCH_CANDIDATE_INQ("OFLWQ002"),    // The FlowBatchLotSelectionInq ID
    FLOATING_BATCH_INQ("OFLWQ003"),
    LOT_VERIFY_FOR_LOADING_REQ("OEQPW003"),         //The CarrierLoadingVerifyReq ID
    /**
     * TxProcessStatusRpt Transaction ID
     */
    PROCESS_STATUS_RPT("OEQPR012"),
    GATE_PASS_REQ("OLOTW005"),                      //The PassThruReq ID

    MOVE_CASSETTE_TO_INTERNAL_BUFFER_RPT("OEQPR008"), // The TxCarrierMoveToIBRpt ID
    MOVE_CASSETTE_FROM_INTERNAL_BUFFER_RPT("OEQPR009"), // The TxCarrierMoveFromIBRpt ID

    NEW_LOT_RELEASE_REQ("OPLNW001"),                // The NewProdOrderCreateReq Transaction ID
    LOG_ON_CHECK_REQ("OACCQ001"),                   // The LoginCheckInq Transaction ID
    HOLD_BANK_LOT_REQ("OBNKW009"),
    HOLD_RELEASE_BANK_LOT_REQ("OBNKW010"),
    PRIVILEGE_CHECK_REQ("OACCQ002"),

    LOT_SCHEDULE_CHANGE_REQ("OPLNW006"),
    LOT_REQUEUE_REQ("OPLNW007"),
    NEW_LOT_UPDATE_REQ("OPLNW003"),


    OPERATION_START_REQ("OEQPW005"),                      // The MoveInReq ID
    OPERATION_START_CANCEL_REQ("OEQPW009"),              // The MoveInCancelReq ID
    OPERATION_START_CANCEL_FOR_INTERNAL_BUFFER_REQ("OEQPW010"), // The MoveInCancelForIBReq ID
    OPERATION_START_FOR_INTERNAL_BUFFER_REQ("OEQPW004"), // The MoveInForIBReq ID
    OBJECTID_LIST_INQ("OPOSQ001"),                        //The ObjectList ID
    ALL_RECIPE_BY_PRODUCTSPECIFICATION_INQ("OAMNQ004"),

    OPERATION_COMP_WITH_DATA_REQ("OEQPW006"),            // The MoveOutReq ID
    OPERATION_COMP_FOR_INTERNAL_BUFFER_REQ("OEQPW008"), // The MoveOutForIBReq ID

    PRODUCT_REQUEST_INQ("OLSTQ002"),                      //The TxProductOrderInq ID;
    PARTIAL_OPERATION_COMP_WITH_DATA_REQ("OEQPW012"),       // The PartialOpenCompWithDataReq ID
    PARTIAL_OPERATION_COMP_FOR_INTERNAL_BUFFER_REQ("OEQPW024"),    // The PartialOpenCompForInternalBufferReq ID
    POST_PROCESS_ACTION_REGIST_REQ("OPOSW002"),                // The PostTaskRegisterReq ID
    /**
     * ForceSkipReq ID
     */
    FORCE_OPE_LOCATE_REQ("OLOTW004"),
    POST_PROCESS_EXEC_REQ("OPOSW001"),      // The PostTaskExecuteReq ID
    RELEASE_LOT_LIST_INQ_REQ("OLSTQ001"),   // The ProductOrderReleasedListInq ID
    PRODUCT_RELATED_SOURCE_PRODUCT_INQ("OPSPQ001"),   // The ProductOrderReleasedListInq ID
    SCRAP_WAFER_CANCEL_REQ("OLOTW041"),      // The TxUnscrapWaferReq ID
    SCRAP_WAFER_REQ("OLOTW043"),             // The TxScrapWaferReq ID
    SCRAP_WAFER_NOT_ON_ROUTE_REQ("OLOTW042"),             // The TxScrapWaferNotOnPfReq ID
    SCRAP_WAFER_NOT_ON_ROUTE_CANCEL_REQ("OLOTW044"),             // The TxUnscrapWaferNotOnPfReq ID
    SCRAP_HISTORY_INQ("OINFQ006"),             // The TxWaferScrappedHistoryInq ID
    USER_DESC_INQ("OACCQ003"),
    USER_LIST_INQ("OACCQ004"),
    OMS_MSG_INFO_INQ("AMSIN001"),
    LOT_CONTAMINATION_UPDATE("OLOTW045"),
    LOT_NPW_USAGE_RECYCLE_LIMIT_UPDATE_REQ("OLOTW046"),
    LOT_NPW_USAGE_RECYCLE_COUNT_UPDATE_REQ("OLOTW047"),
    LOT_TERMINATE_REQ("OLOTW038"),                          // Lot Terminate
    LOT_TERMINATE_CANCEL_REQ("OLOTW039"),                   // Lot Terminate Cancel



    STB_CANCEL_INFO_INQ("OLSTQ006"), //TxWaferLotStartCancelInfoInq
    STB_CANCEL_REQ("OLSTW002"),     // TxWaferLotStartCancelReq
    START_LOTS_RESERVATION_REQ("ODISW001"),        // The MoveInReserveReq ID
    START_LOTS_RESERVATION_CANCEL_REQ("ODISW002"),        // The MoveInReserveCancelReq ID
    START_LOTS_RESERVATION_FOR_INTERNAL_BUFFER_REQ("ODISW003"),     // The MoveInReserveForIBReq ID
    START_LOTS_RESERVATION_CANCEL_FOR_INTERNAL_BUFFER_REQ("ODISW004"),     // The MoveInReserveCancelForIBReq ID
    SOURCE_LOT_INQ("OLSTQ005"),         //  The SourceLotListInq ID
    START_LOTS_RESERVATION_FOR_TAKE_OUT_IN_REQ("ODISW009"),   //  The MoveInReserveForTOTIReq ID

    STB_RELEASED_LOT_REQ("OLSTW001"),
    SUB_LOT_TYPE_ID_LIST_INQ("OCONQ005"),            //

    REFLOW_BATCHING_REQ("OFLWW006"),

    FORCE_DYNAMIC_REWORK_REQ("OLOTW009"),
    FORCE_REWORK_REQ("OLOTW011"),
    DYNAMIC_REWORK_REQ("OLOTW008"),
    REWORK_REQ("OLOTW010"),
    REWORK_WHOLE_LOT_REQ("OLOTW050"),

    REWORK_WHOLE_LOT_CANCEL_REQ("OLOTW012"),
    DYNAMIC_ROUTE_LIST_INQ("OLOTQ014"),

    PARTIAL_REWORK_WITH_HOLD_RELEASE_REQ_ONE("OLOTW023"),
    PARTIAL_REWORK_WITH_HOLD_RELEASE_REQ_POST_PROC_ONE("TcEWC020"),
    PARTIAL_REWORK_WITH_HOLD_RELEASE_REQ_TWO("OLOTW025"),
    PARTIAL_REWORK_WITH_HOLD_RELEASE_REQ_POST_PROC_TWO("TcTRC087"),
    PARTIAL_REWORK_WITH_HOLD_RELEASE_REQ_THREE("OLOTW022"),
    PARTIAL_REWORK_WITH_HOLD_RELEASE_REQ_POST_PROC_THREE("TcEWC019"),
    PARTIAL_REWORK_WITH_HOLD_RELEASE_REQ_FOUR("OLOTW024"),
    PARTIAL_REWORK_WITH_HOLD_RELEASE_REQ_POST_PROC_FOUR("TcTRC069"),


    REWORK_WITH_HOLD_RELEASE_REQ_ONE("OLOTW014"),
    REWORK_WITH_HOLD_RELEASE_REQ_TWO("OLOTW016"),
    REWORK_WITH_HOLD_RELEASE_REQ_THREE("OLOTW013"),
    REWORK_WITH_HOLD_RELEASE_REQ_FOUR("OLOTW015"),


    VENDOR_LOT_PREPARATION_REQ("OBNKW003"),        // The MaterialPrepareReq Transaction ID
    VENDOR_LOT_PREPARATION_AND_PREPARE_REQ("OBNKW004"), // TxMaterialReceiveAndPrepareReq ID

    LOT_PREPARATION_CANCEL_REQ("OBNKW005"),        // The LotPreparationReq TransactionID

    VEND_LOT_RECEIVE_REQ("OBNKW001"),              // The MaterialReceiveReq Transaction ID
    VEND_LOT_RETURN_REQ("OBNKW002"),                // The MaterialReturnReq Transaction ID

    WAFER_SORTER_RPT("OSRTR003"),                    // The WaferSlotmapChangeRpt Transaction ID
    WAFER_SORTER_REQ("OSRTW007"),                    // The WaferSlotmapChangeReq Transaction ID

   //WAFER_SORTER_POSITION_ADJUST_REQ("OSRTW001"),         //  The OnlineSorterSlotmapAdjustReq Transaction ID
    WAFER_SORTER_ON_EQP_RPT("OSRTR001"),           // The OnlineSorterRpt Transaction ID
  //WAFER_SORTER_ACTION_LIST_INQ("OSRTQ001"), //The TxOnlineSorterActionSelectionInq ID
    WAFER_SORTER_ON_EQP_REQ("OSRTW004"), // TxOnlineSorterActionExecuteReq ID

    WAFER_SORTER_ON_EQP_CANCEL_REQ("OSRTW005"),  //TxOnlineSorterActionCancelReq ID
   // WAFER_SORTER_DATA_COMPARE_REQ("OSRTW006"),  // TxOnlineSorterSlotmapCompareReq
    WAFER_SORTER_DATA_INQ("OSRTQ002"),  // TxOnlineSorterActionStatusInq ID
    WAFER_SORTER_SCRAP_WAFER_INQ("OSRTQ003"), // TxOnlineSorterScrapWaferInq ID
 //   SORT_JOB_CREATE_REQ("OSRTW009"), // TxSJCreateReq ID
 //   SORT_JOB_CANCEL_REQ("OSRTW008"), // TxSJCancelReq ID
 //   SORT_JOB_PRIORITY_CHANGE_REQ("OSRTW010"), // TxSortJobPriorityChangeReq ID
 //   SORT_JOB_STATUS_CHANGE_RPT("OSRTR002"), // TxSortJobStatusChangeRpt ID
  //  SORT_JOB_LIST_INQ("OSRTQ005"), // TxSJListInq ID
    SORT_JOB_STATUS_LIST_INQ("OSRTQ006"), // TxSortJobStatusListInq ID
    GET_CATEGORY_BY_LOT_INQ("OSRTQ007"), //
    SORT_JOB_START_REQ("OSRTW011"), // TxSJStartReq ID
  //  SJ_CONDITION_CHECK_REQ("OSRTQ004"), // TxSJConditionCheckReq ID

    WHAT_NEXT_LOT_LIST_FOR_INTERNAL_BUFFER_INQ("OTMSQ009"),  // The TxWhatNextLotListForInternalBufferInq ID
    BANK_MOVE_REQ("OBNKW008"),                      // The BankMoveReq Transaction ID
    SHIP_REQ("OBNKW011"),                           // The ShipReq Transaction ID
    SHIP_CANCEL_REQ("OBNKW012"),                   // The UnshipReq Transaction ID
    LOT_INFO_INQ("OLOTQ001"),                      // The TxLotInfoInq__150 Transaction ID
    LOT_MFG_ORDER_CHANGE_REQ("OPLNW004"),                      // The TxProdOrderChangeReq Transaction ID
    LOT_CASSETTE_TAKE_OUT_IN_INQ("OTMSW013"),     // The LotCassetteTakeOutInInq ID
    LOT_LIST_IN_CASSETTE_INQ("OLOTQ003"),         // The TxLotListInqCassetteInq Transaction ID
    WHATNEXT_LOT_LIST_INQ("ODISQ001"),          // The TxWhatNextInq__140 Transaction ID
    WHAT_NEXT_EQP_MONITOR_LOT_LIST_INQ("OAMNQ003"),          // The TxWhatNextAMLotInq Transaction ID
    REASON_LIST_INQ("OSYSQ003"),
    WHERE_NEXT_INTER_BAY_INQ("OTMSQ005"),
    DURABLE_WHERE_NEXT_INTER_BAY_INQ("OTMSQ010"),
    LOT_AUTO_DISPATCH_CONTROL_INFO_INQ("ODISQ005"),
    AUTO_DISPATCH_CONTROL_UPDATE_REQ("ODISW005"),
    /**
     * The TxEqpRecipeParameterListInq Transaction ID
     */
    EQP_RECIPE_PARAMETER_LIST_INQ("OEQPQ015"),
    /**
     * The TxEqpBufferInfoInq Transaction ID
     */
    EQP_BUFFER_RESOURCE_INFO_INQ("OEQPQ012"),
    EQP_ALARM_HISTORY_INQ("OINFQ007"),
    COMMON_EQP_INFO_INQ("OEQPQ005"),                //The TxGeneralEqpInfoInq Transaction ID
    EQP_INFO_INQ("OEQPQ001"),                       // The TxEqpInfoInq__120 Transaction ID
    DATA_SPEC_CHECK_REQ("OEDCW001"),                   // The TxSpecCheckReq Transaction ID
    DATA_SEND_COMPLETE_RPT("OEDCR003"),
    DATA_UPDATE_FORLOT_REQ("OEDCW004"),
    SPC_CHECK_REQ("OEDCW002"),
    SPC_ACTION_EXECUTE_REQ("OEDCW007"),
    LOT_LIST_IN_BONDING_FLOW_INQ("TXDSQ021"), // TxLotListByBondingFlowInq ID
    LOT_HOLD_LIST_INQ("OLOTQ006"),                   // The TxHoldLotListInq Transaction ID
    LOTS_INFO_FOR_OPERATION_START_INQ("OEQPQ006"),   // The TxLotsMoveInInfoInq ID
    LOTS_INFO_FOR_START_RESERVATION_INQ("ODISQ002"), // The TxLotsMoveInReserveInfoInq ID
    LOTS_INFO_FOR_OPERATION_START_FOR_INTERNAL_BUFFER_INQ("OEQPQ007"),  // TxLotsMoveInInfoForIBInq ID
    LOTS_INFO_FOR_START_RESERVATION_FOR_INTERNAL_BUFFER_INQ("ODISQ003"),  //TxLotsMoveInReserveInfoForIBInq ID
    LOADING_LOT_RPT("OEQPR001"),   // The TxCarrierLoadingRpt ID
    LOADING_LOT_FOR_INTERNAL_BUFFER_RPT("OEQPR002"), // TxCarrierLoadingForIBRpt ID

    HOLD_LOT_REQ("OLOTW001"),
    HOLD_LOT_RELEASE_REQ("OLOTW002"),
    OPE_LOCATE_REQ("OLOTW003"),


    PROCESS_LAG_TIME_UPDATE_REQ("OPRCW008"),
    UN_LOADING_LOT_RPT("OEQPR005"), // The TxCarrierUnloadingRpt ID
    UN_LOADING_LOTS_RESERVATION_FOR_INTERNAL_BUFFER_RPT("OEQPR013"), // The ReserveUnloadingLotsForIBRpt ID
    UN_LOADING_LOTS_RESERVATION_CANCEL_FOR_INTERNAL_BUFFER_REQ("OEQPW021"),
    UN_LOADING_LOT_FOR_INTERNAL_BUFFER_RPT("OEQPR006"), // The TxCarrierUnloadingForIBRpt D
    CANDIDATE_EQP_STATUS_INQ("OEQPQ008"),
    ENHANCED_FUTURE_HOLD_REQ("OPRCW001"), // The TxFutureHoldReq ID
    FUTURE_HOLD_CANCEL_REQ("OPRCW002"), // The TxFutureHoldCancelReq ID
    FUTURE_HOLD_LIST_INQ("OPRCQ001"), // 找不到TransactionID
    /**
     * TxAllProductGroupListInq Transaction ID
     */
    PRODUCT_GROUP_ID_LIST_INQ("OLSTQ004"),
    LOT_OPERATION_LIST_INQ("OLOTQ010"), // The TxLotOperationSelectionInq__160 ID
    LOT_INFO_FOR_OPE_START_FOR_INTERNAL_BUFFER_INQ("OEQPQ007"),
    SPLIT_WAFER_LOT_REQ("OLOTW030"),
    WAFER_SORT_REQ("OSRTW007"),
    CANDIDATE_CHAMBER_STATUS_INQ("OEQPQ010"),
    ENTITY_INHIBIT_LIST_INQ("OCONQ001"),
    ENTITY_INHIBIT_LIST_BY_EQP_INQ("OCONQ007"),
    ENTITY_INHIBIT_EXCEPTION_LOT_LIST_INQ("OCONQ002"),
    ENTITY_INHIBIT_RECIPE_TIME_INQ("OCONQ006"),
    CONNECTED_ROUTE_LIST_INQ("OLOTQ013"),
    LOT_FAMILY_INQ("OLOTQ004"),
    BANK_IN_REQ("OBNKW015"), // The TxBankInReq ID
    BANK_IN_CANCEL_REQ("OBNKW007"), // The TxBankInCancelReq ID
    DATA_ITEM_WITH_TEMP_DATA_INQ("OEDCQ001"),
    ENTITY_INHIBIT_REQ("OCONW001"),
    ENTITY_INHIBIT_EXCEPTION_LOT_REQ("OCONW003"),
    ENTITY_INHIBIT_EXCEPTION_LOT_CANCEL_REQ("OCONW004"),
    ENTITY_INHIBIT_RECIPE_TIME_REQ("OCONW005"),
    ENTITY_INHIBIT_MODIFY_REQ("OCONW007"),
    ENTITY_INHIBIT_RECIPE_TIME_CANCEL("OCONW006"),
    ENTITY_INHIBIT_IMPORT_REQ("OCONW008"),
    ENTITY_INHIBIT_EXPORT_INQ("OCONQ008"),
    SPLIT_WAFER_LOT_WITH_HOLD_RELEASE_REQ("OLOTW031"),
    SPLIT_WAFER_LOT_WITH_OUT_HOLD_RELEASE_REQ("OLOTW032"),
    SPLIT_WAFER_LOT_NOT_ON_ROUTE_REQ("OLOTW040"),
    ENTITY_INHIBIT_CANCEL_REQ("OCONW002"),
    LOT_INFO_BY_WAFER_INQ("OLOTQ005"),
    MACHINE_RECIPE_ID_LIST_INQ("ORCPQ003"),
    RETICLE_GROUP_ID_LIST_INQ("ODRBQ012"),
    RETICLE_ID_LIST_INQ("ODRBQ013"),
    ROUTE_OPERATION_LIST_INQ("OLOTQ016"),
    ALL_LOT_TYPE_LIST_INQ("OLOTQ018"),
    NON_PRO_BANK_IN_REQ("OBNKW013"), // The TxNonProdBankStoreReq ID
    NON_PRO_BANK_OUT_REQ("OBNKW014"), // The TxNonProdBankStoreReq ID
    MERGE_WAFER_LOT_REQ("OLOTW033"),
    NEW_LOT_RELEASE_CANCEL_REQ("OPLNW002"),
    PRODUCT_ID_LIST_INQ("OLSTQ003"),
    VENDOR_LOT_RECEIVE_AND_PREPARE_REQ("OBNKW004"),
    ALIAS_WAFER_NAME_SET_REQ("OLSTW003"),
    WAFER_LIST_IN_LOT_FAMILY_INFO("OLOTQ019"),
    WAFER_ALIAS_NAME_INFO_INQ("OLOTQ020"),
    MERGE_WAFER_LOT_NOT_ON_ROUTE_REQ("OLOTW034"),
    TMS_TRANSPORT_JOB_CREATE_REQ("S01"),
    LOT_COMMENT_INFO_INQ("OINFQ009"),
    LOT_LIST_IN_CONTROL_JOB_INQ("OLOTQ007"),
    LOT_NOTE_INFO_INQ("OINFQ010"),
    LOT_OPERATION_NOTE_INFO_INQ("OINFQ011"),
    LOT_OPERATION_NOTE_LIST_INQ("OINFQ012"),
    MFG_LAYER_LIST_INQ("OLOTQ022"),
    LOT_NOTE_INFO_REGIST_REQ("OINFW002"),
    MULTIPLE_LOTS_OPERATION_LIST_INQ("OLOTQ024"),
    LOT_OPERATION_NOTE_INFO_REGISTER_REQ("OINFW003"),
    MODULE_PROCESS_DEFINITION_ID_LIST_INQ("OCONQ003"),
    PROCESS_DEFINITION_ID_LIST_INQ("OLOTQ025"),
    ROUTE_INDEX_LIST_INQ("OLOTQ026"),
    STAGE_ID_LIST_INQ("OCONQ004"),
    SUBROUT_BRABCH_CANCEL_REQ("OLOTW037"),
    FUTURE_HOLD_LIST_BY_KEY("OPRCQ001"),
    LOT_EXTERNAL_PRIORITY_CHANGE_REQ("OPLNW005"),
    ROUTE_OPERATION_LIST_FOR_LOT_INQ("OLOTQ017"),
    ROUTE_OPERATION_NEST_LIST_INQ("ODOCQ004"),
    VIRTUAL_OPERATION_LOT_LIST_INQ("ODISQ006"),
    MONITOR_LOT_STB_AFTER_PROCESS_REQ("OPMNW003"),
    PROCESS_HOLD_REQ("OPRCW006"),
    WHAT_NEXT_STANDBY_LOT_INQ("ODISQ004"),
    RETICLE_POD_PMINFO_RESET_REQ("ODRBW007"),
    RETICLE_POD_MULTI_STATUS_CHANGE_RPT("ODRBR006"),
    MAKE_RELATION_MONITOR_PROD_LOTS_REQ("OPMNW001"),
    LOT_PREPARATION_CANCEL_INFO_INQ("OBNKQ002"),
    MONITOR_PROD_LOTS_RELATION_INQ("OPMNQ001"),
    CIPJ_INFO_INQ("OCJPQ001"),
    CIPJ_PROGRESS_INQ("OCJPQ002"),
    EQP_MONITOR_LIST_INQ("OAMNQ001"),
    EQP_MONITOR_JOB_LIST_INQ("OAMNQ002"),
    EQP_MONITOR_STATUS_CHANGE_RPT("OAMNR001"),
    EQP_MONITOR_LOT_RESERVE_REQ("OAMNW002"),
    EQP_MONITOR_JOB_STATUS_CHANGE_RPT("OAMNR002"),
    EQP_MONITOR_UPDATE_RPT("OAMNW001"),
    EQP_MONITOR_SCHEDULE_UPDATE_REQ("OAMNW006"),
    EQP_MONITOR_RESET_REQ("OAMNW005"),
    EQP_MONITOR_WAFER_USED_COUNT_UPDATE_REQ("TXPCC060"),
    ARRIVAL_CARRIER_CANCEL_REQ("OTMSW010"),
    ARRIVAL_CARRIER_CANCEL_FOR_INTERNAL_BUFFER_REQ("OTMSW012"),
    CANCEL_RELATION_MONITOR_PROD_LOTS_REQ("OPMNW002"),

    PARTIAL_REWORK_FORCE_AND_DYNAMIC_ROUTE("OLOTW018"),
    PARTIAL_REWORK_FORCE("OLOTW020"),
    PARTIAL_REWORK_DYNAMIC_ROUTE("OLOTW017"),
    PARTIAL_REWORK("OLOTW019"),

    POST_PARTIAL_REWORK_FORCE_AND_DYNAMIC_ROUTE("TcEWC007"),
    POST_PARTIAL_REWORK_FORCE("TcTRC047"),
    POST_PARTIAL_REWORK_DYNAMIC_ROUTE("TcEWC006"),
    POST_PARTIAL_REWORK("TcTRC028"),
    CTRL_LOT_STB_REQ("OLSTW004"),
    SINGLE_CARRIER_XFER_REQ("OTMSW006"),
    MULTI_CARRIER_XFER_REQ("OTMSW005"),
    RETICLE_POD_BASE_INFO_LIST_INQ("ODRBQ011"),
    COLLECTED_DATA_ACTION_REQ("OEDCW003"),
    TEMP_DATA_RPT("OEDCR001"),

    PARTIAL_REWORK_WITHOUT_HOLD_RELEASE_REQ_SPECIAL_ENGINEERING("OLOTW027"),
    PARTIAL_REWORK_WITHOUT_HOLD_RELEASE_REQ_SPECIAL_ENGINEERING_POST_PROC("TcEWC022"),
    PARTIAL_REWORK_WITHOUT_HOLD_RELEASE_REQ_SPECIAL("OLOTW029"),
    PARTIAL_REWORK_WITHOUT_HOLD_RELEASE_REQ_SPECIAL_POST_PROC("TcTRC088"),
    PARTIAL_REWORK_WITHOUT_HOLD_RELEASE_REQ_ENGINEERING("OLOTW026"),
    PARTIAL_REWORK_WITHOUT_HOLD_RELEASE_REQ_ENGINEERING_POST_PROC("TcEWC021"),
    PARTIAL_REWORK_WITHOUT_HOLD_RELEASE_REQ("OLOTW028"),
    PARTIAL_REWORK_WITHOUT_HOLD_RELEASE_REQ_POST_PROC("TcTRC073"),

    REWORK_PARTIAL_WAFER_LOT_CANCEL_REQ("OLOTW021"),
    BRANCH_REQ("OLOTW006"),
    SUB_ROUTE_BRANCH_REQ("OLOTW035"),
    BRANCH_WITH_HOLD_RELEASE_REQ("OLOTW007"),
    LOT_CTRL_STATUS_CHANGE_REQ("OPRCW003"),
    LOT_CTRL_STATUS_INQ("OPRCQ002"),
    LOT_CASSETTE_RESERVE_REQ("OTMSW003"),
    LOT_CASSETTE_RESERVE_CANCEL_REQ("OTMSW004"),
    QREST_TIME_LIST_INQ("OPRCQ008"),
    QREST_TIME_UPDATE_REQ_ACTION_CREATE("OPRCW019"),
    QREST_TIME_UPDATE_REQ_ACTION_UPDATE("OPRCW017"),
    QREST_TIME_UPDATE_REQ_ACTION_DELETE("OPRCW018"),
    LOT_FUTURE_ACTION_LIST_INQ("OPRCQ004"),
    DATA_COLLECTION_ITEM_LIST_INQ("OEDCQ008"),
    CANDIDATE_DURABLE_SUB_STATUS_INQ("ODRBQ005"),
    COLLECTED_DATA_ITEM_INQ("OEDCQ009"),
    LOT_FUTURE_ACTION_DETAIL_INFO("OLOTQ015"),
    FLOW_BATCH_LOST_LOTS_INQ("OFLWW007"),
    /**
     * The TxUploadedRecipeIdListByEqpInq Transaction ID
     */
    MACHINE_RECIPE_LIST_INQ("ORCPQ001"),
    MACHINE_RECIPE_LIST_FOR_FPC_INQ("ODOCQ003"),
    LOT_OPERATION_LIST_FROM_HISTORY_INQ("OINFQ002"),
    OPERATION_HISTORY_INQ("OINFQ001"),
    HISTORY_INFORMATION_INQ("OINFQ005"),
    OPE_COMP_FOR_INTERNAL_BUFFER_REQ("OEQPW008"),
    FLOW_BATCH_INQ("OFLWQ001"),
    DATA_COLLECTION_LIST_INQ("OEDCQ007"),
    LOT_VERIFY_FOR_LOADING_FOR_INTERNAL_BUFFER_REQ("OEQPW007"),
    COLLECTED_DATA_HISTORY_INQ("OINFQ004"),
    MON_LOT_COLLECTED_DATA_HISTORY_INQ("OINFQ016"),
    PROCESS_HOLD_CANCEL_REQ("OPRCW007"),
    PROCESS_HOLD_LIST_INQ("OPRCQ005"),
    FLOW_BATCH_OPE_LOCATE_CHECK_REQ("OFLWW009"),
    USER_DATA_INQ("OCDAQ001"),
    USER_DATA_UPDATE_REQ("OCDAW001"),
    USER_PARAMETER_VALUE_CHANGE_REQ("OPCSW001"),
    USER_PARAMETER_VALUE_INQ("OPCSQ001"),
    LOT_ASSETTE_XFER_JOB_COMP_RPT("OTMSR002"),

    DURABLE_STATUS_MULTI_CHANGE_REQ_RETICLE("ODRBW004"),
    DURABLE_STATUS_MULTI_CHANGE_REQ_RETICLE_POD("ODRBW005"),
    DURABLE_STATUS_MULTI_CHANGE_REQ_CARRIER("ODRBW003"),
    DUARBLE_XFER_JOB_STATUS_RPT("OTMSR003"),
    FPCPROCESS_LIST_IN_ROUTE_INQ("ODOCQ002"),
    FPCDETAIL_INFO_INQ("ODOCQ001"),
    FPCDELETE_REQ("ODOCW002"),
    EXPERIMENTAL_LOT_LIST_INQ("OPSMQ002"),
    FPC_EXEC_REQ("ODOCW003"),

    FPC_DELETE_REQ("ODOCW002"),

    FPC_UPDATE_REQ("ODOCW001"),
    EXPERIMENTAL_LOT_INFO_INQ("OPSMQ001"),
    EXPERIMENTAL_LOT_DELETE_REQ("OPSMW003"),
    EXPERIMENTAL_LOT_UPDATE_REQ("OPSMW001"),
    COLLECTED_DATA_BY_PJ_RPT("OEDCR002"),
    RUNNING_HOLD_REQ("OEQPW020"),
    FORCE__OPE_COMP_REQ("OEQPW014"),
    FORCE_OPE_COMP_FOR_INTERNAL_BUFFER_REQ("OEQPW023"),
    EQP_ALARM_RPT("OEQPR014"),
    EXPERIMENTAL_LOT_EXEC_REQ("OPSMW002"),

    RETICLE_STOCKER_INFO_INQ("ODRBQ010"),
    LOT_CASSETTE_XFER_JOB_INQ("OTMSQ003"),
    LOT_CASSETTE_XFER_JOB_DETAIL_INQ("OTMSQ004"),
    LOT_CASSETTE_XFER_JOB_DELETE_REQ("OTMSW007"),
    TCS_RECOVERY_REQ("OEQPW013"),
    RETICLE_SORT_RPT("ODRBR009"),
    BULLETIN_BOARD_INFO_REGIST("OINFW001"),
    BULLETIN_BOARD_INFO_INQ("OINFQ003"),
    RECIPE_DOWNLOAD_REQ("ORCPW001"),
    ARRIVAL_CARRIER_NOTIFICATION_REQ("OTMSW008"),
    ARRIVAL_CARRIER_NOTIFICATION_FOR_INTERNAL_BUFFER_REQ("OTMSW009"),
    RECIPE_FILE_DELETION_REQ("ORCPW005"),
    RECIPE_CONFIRMATION_REQ("ORCPW003"),
    PROCESS_JOB_INFO_RPT("OCJPR002"),
    PROCESS_JOB_MAP_INFO_RPT("TXEQR013"),
    PROCESS_JOB_MANAGE_REQ("OCJPW002"),
    RECIPE_DIRECTORY_INQ("ORCPQ002"),
    RECIPE_UPLOAD_REQ("ORCPW002"),
    RECIPE_DELETION_REQ("ORCPW004"),
    PROCESS_JOB_STATUS_CHANGE_RPT("OCJPR001"),
    RECIPE_PARAMETER_ADJUST_RPT("OPRCR001"),
    OWNER_CHANGE_REQ("OACCW001"),
    SYSTEM_MSG_RPT("OSYSR001"),
    COLLECTED_DATA_INFO_FOR_UPDATE_INQ("OEDCQ006"),
    SCHEDULE_CHANGERESERVATION_LIST_INQ("OPLNQ002"),
    SCHEDULE_CHANGERESERVATION_CREATE_REQ("OPLNW010"),
    SCHEDULE_CHANGERESERVATION_CANCEL_REQ("OPLNW008"),
    SCHEDULE_CHANGERESERVATION_CHANGE_REQ("OPLNW009"),
    SCHEDULE_CHANGERESERVATION_EXECUTE_REQ("OPLNW012"),
    POST_PROCESS_ACTION_UPDATE("OPOSW007"),
    POST_PROCESS_FORCE_DELETE_REQ("OPOSW006"),
    PCS_RUN_REQ("OPCSW002"),
    WIPLOT_RESET_REQ("OPLNW013"),
    POST_PROCESS_ACTION_LIST_INQ("OPOSQ003"),
    EXTERNAL_POST_PROCESS_FILTER_REGIST_REQ("OPOSW005"),
    EXTERNAL_POST_PROCESS_FILTER_DELETE_REQ("OPOSW004"),
    EXTERNAL_POST_PROCESS_FILTER_LIST_INQ("OPOSQ002"),
    FUTURE_REWORK_REQ("OPRCW009"),
    FUTURE_REWORK_LIST_INQ("OPRCQ007"),
    FUTURE_REWORK_EXEC_REQ("OPRCW014"),

    /** APC  */
    APC_CAPABILITY_INQ("TXAPQ001"),
    APC_RECIPE_PARAMETER_ADJUST_INQ("TXAPQ008"),
    APC_IF_LIST_INQ("OAPCQ003"),
    ENTITY_LIST_INQ("TXAPQ011"),
    APC_IF_POINT_REQ("OAPCW003"),

    //--------------------------
    // parts
    //--------------------------
    BOM_PARTS_INQ("OPTSQ001"),
    BOM_PARTS_FOR_LOT_LIST_INQ("OPTSQ002"),


    //--------------------------
    // bonding
    //--------------------------
    BONDING_FLOW_LIST_INQ("OBNDQ001"),
    BONDING_GROUP_LIST_INQ("OBNDQ002"),
    BONDING_LOT_LIST_IINQ("OBNDQ003"),
    EQP_BONDING_CANDIDATE_INQ("OBNDQ004"),
    LOT_LIST_BY_BONDING_FLOW_INQ("OBNDQ005"),
    BONDED_WAFER_LIST_INQ("OBNDQ006"),

    BONDING_GROUP_MODIFY_REQ("OBNDW001"),
    BONDING_GROUP_PARTIAL_REMOVE_REQ("OBNDW002"),
    WAFER_BOND_REQ("OBNDW003"),
    WAFER_BOND_CANCEL_REQ("OBNDW004"),

    BONDING_MAP_RPT("OBNDR001"),

    //--------------------------
    //  FMC
    //--------------------------
    FMC_CARRIER_REMOVE_FROM_CJ_REQ("OFMCW001"),
    FMC_CARRIER_UNCLAMP_REQ("OFMCW002"),
    FMC_MOVE_IN_RESERVE_REQ("OFMCW003"),
    FMC_MODE_CHANGE_REQ("OFMCW004"),
    FMC_RSV_MAX_COUNT_UPDATE_REQ("OFMCW006"),
    FMC_WAFER_RETRIEVE_CARRIER_RESERVE_REQ("OFMCW005"),

    FMC_PROCESS_JOB_STATUS_RPT("OFMCR001"),
    FMC_WAFER_STORE_RPT("OFMCR003"),
    FMC_WAFER_RETRIEVE_RPT("OFMCR002"),

    SLM_START_LOTS_RECEIVE_MAX_COUNT_UPDATE_REQ("TXTRC081"),

    SLM_CASSETTE_UNCLAMP_REQ ("Inputs.SendSLMCassetteUnclampReqIn"),

    SEASON_PLAN_CREATE_REQ ("OSSNW001"),

    SEASON_PLAN_MODIFY_REQ ("OSSNW002"),

    SEASON_PLAN_DELETE_REQ ("OSSNW003"),

    SEASON_PLANS_DELETE_REQ ("OSSNW004"),

    SEASON_RECIPE_GROUP_CREATE_REQ ("OSSNW005"),

    SEASON_RECIPE_GROUP_MODIFY_REQ ("OSSNW006"),

    SEASON_RECIPE_GROUP_DELETE_REQ ("OSSNW007"),

    SEASON_JOB_ABORT_REQ ("OSSNW008"),

    SEASON_PRIORITY_REQ ("OSSNW009"),

    SEASON_OPERATION_REQ ("OSSNW010"),

    SEASON_LOT_MOVE_IN_RESERVE_REQ ("OSSNW011"),

    SEASONMOVE_IN_RESERVE_REQ("OSSNW012"),

    SEASON_MOVE_IN_RESERVE_REQ("OSSNW013"),

    SEASON_MOVE_IN_RESERVE_FOR_IB_REQ("OSSNW014"),

    MACHINE_SEASON_PLAN_INQ("OSSNQ001"),

    SEASON_PLAN_INFO_INQ("OSSNQ002"),

    RECIPE_GROUP_INFO_INQ("OSSNQ003"),

    MACHINE_SEASON_JOB_INQ("OSSNQ004"),

    SEASON_JOB_INFO_INQ("OSSNQ005"),

    SEASON_TYPES_INQ("OSSNQ006"),

    ALL_SEASON_STATUS_INQ("OSSNQ008"),

    RECIPE_GROUP_INQ("OSSNQ007"),

    ALL_SEASON_JOB_STATUS_INQ("OSSNQ009"),

    SEASON_WHAT_NEXT_INQ("OSSNQ010"),

    SEASON_LOTS_MOVE_IN_RESERVE_INFO_INQ("OSSNQ011"),

    SEASON_LOTS_MOVE_IN_RESERVE_INFO_FOR_IB_INQ("OSSNQ012"),

    //-------------------------------
    // For DMS
    //-------------------------------
    DURABLES_INFO_FOR_START_RESERVATION_INQ("ODRBQ024"),
    DURABLE_OPERATION_LIST_INQ("ODRBQ022"),
    DURABLE_OPERATION_LIST_FROM_HISTORY_INQ("ODRBQ021"),
    DURABLE_OPERATION_HISTORY_INQ("ODRBQ020"),
    DURABLE_HOLD_LIST_INQ("ODRBQ019"),
    ROUTE_OPERATION_LIST_FOR_DURABLE_INQ("ODRBQ031"),
    DURABLE_CONTROL_JOB_LIST_INQ("ODRBQ018"),
    DURABLES_INFO_FOR_OPE_START_INQ("ODRBQ023"),
    START_DURABLES_RESERVATION_REQ("ODRBW043"),
    START_DURABLES_RESERVATION_FOR_IB_REQ("ODRBW044"),
    START_DURABLES_RESERVATION_CANCEL_REQ("ODRBW042"),
    START_DURABLES_RESERVATION_CANCEL_FOR_IB_REQ("ODRBW045"),
    DURABLE_OPERATION_START_REQ("ODRBW029"),
    DURABLE_OPERATION_START_FOR_IB_REQ("ODRBW046"),
    DURABLE_OPERATION_START_CANCEL_REQ("ODRBW028"),
    DURABLE_OPERATION_START_CANCEL_FOR_IB_REQ("ODRBW047"),
    DURABLE_OPE_COMP_REQ("ODRBW026"),
    DURABLE_OPE_COMP_FOR_IB_REQ("ODRBW048"),
    DURABLE_PFX_CREATE_REQ("ODRBW030"),
    DURABLE_PFX_DELETE_REQ("ODRBW031"),
    DURABLE_POST_PROCESS_ACTION_REGIST_REQ("ODRBW032"),
    DURABLE_LAG_TIME_UPDATE_REQ("ODRBW039"),
    DURABLE_JOB_STATUS_SELECTION_INQ("ODRBQ025"),
    DURABLE_JOB_STATUS_CHANGE_REQ("ODRBW053"),
    REWORK_DURABLE_WITH_HOLD_RELEASE_REQ("ODRBW054"),
    DURABLE_JOB_STATUS_CHANGE_RPT("ODRBR053"),
    DURABLE_BANK_IN_LIST_INQ("ODRBR054"),

    HOLD_DURABLE_RELEASE_REQ("ODRBW035"),
    HOLD_DURABLE_REQ("ODRBW036"),
    DURABLE_FORCE_OPE_LOCATE_REQ("ODRBW024"),
    DURABLE_BANK_IN_BY_POST_PROC_REQ("ODRBW018"),
    REWORK_DURABLE_CANCEL_REQ("ODRBW037"),
    REWORK_DURABLE_REQ("ODRBW038"),
    FORCE_REWORK_DURABLE_REQ("ODRBW039"),
    CONNECTED_DURABLE_ROUTE_LIST_INQ("ODRBQ033"),


    RC_LIST_INQ("ORUNQ001"),
    RC_UPDATE_REQ("ORUNW001"),
    RC_DELETE_REQ("ORUNW002"),
    RC_APPROVAL_REQ("ORUNW003"),
    RC_STATE_CHANGE_REQ("ORUNW004"),
    RC_PSM_ADD_REQ("ORUNW005"),
    RC_PSM_DELETE_REQ("ORUNW006"),
    RC_DOC_ADD_REQ("ORUNW007"),
    RC_DOC_DELETE_REQ("ORUNW008"),
    RC_COPY_FROM_INQ("ORUNQ002"),

    ER_POD_INFO_INQ("ER00Q001"), //erack

    //-------------------------------
    // For ARHS
    //-------------------------------
    WHAT_RETICLE_ACTION_LIST_INQ("OARHQ006"),//old: TXDSQ016 new: OARHQ006
    WHAT_RETICLE_RETRIEVE_INQ("OARHQ005"),//old: TXDSQ015 new: OARHQ005
    WHERE_NEXT_FOR_RETICLE_POD_INQ("OARHQ001"),//old: TXDSQ017 new: OARHQ001
    ASYNC_RETICLE_XFER_JOB_CREATE_REQ("OARHW018"), //old:TXPDC037 new OARHW018
    EQP_RSP_PORT_ACCESS_MODE_CHANGE_REQ("ODRBW017"), // old: TXEQC019 new: ODRBW017
    RETICLE_OFFLINE_RETRIEVE_REQ("ODRBW010"),// old: TXPDC026 new: ODRBW010
    RETICLE_POD_STOCKER_INFO_INQ("ODRBQ016"),//old: TXPDQ018 new: ODRBQ016
    EQP_RSP_PORT_STATUS_CHANGE_RPT("ODRBR010"),// old: TXEQR012 new: ODRBR010
    RSP_XFER_STATUS_CHANGE_RPT("OARHR003"),//old: TXPDR023 new: OARHR003
    RETICLE_RETRIEVE_REQ("ODRBW015"),// old: TXPDC028 new: ODRBW015
    RETICLE_ACTION_RELEASE_ERROR_REQ("OARHW008"),//old: TXPDC020 new OARHW008
    RETICLE_ACTION_RELEASE_REQ("OARHW003"),//old: TXPDC015 new OARHW003
    RETICLE_DISPATCH_JOB_CANCEL_REQ("OARHW002"),//old: TXPDC014 new OARHW002
    RETICLE_OFFLINE_STORE_REQ("ODRBW011"),// old: TXPDC023 new: ODRBW011
    RETICLE_COMPONENT_JOB_RETRY_REQ("OARHW006"),//old: TXPDC018 new: OARHW006
    RETICLE_COMPONENT_JOB_SKIP_REQ("OARHW007"),//old: TXPDC019 new: OARHW007
    RETICLE_DISPATCH_JOB_DELETE_REQ("OARHW001"),//old: TXPDC013 new: OARHW001
    RETICLE_DISPATCH_JOB_INSERT_REQ("OARHW005"),//old: TXPDC017 new: OARHW005
    RETICLE_RETRIEVE_JOB_CREATE_REQ("OARHW011"),//old: TXPDC027 new OARHW011
    RETICLE_RETRIEVE_RPT("ODRBR014"),// old:TXPDR019  new: ODRBR014
    RETICLE_STORE_JOB_CREATE_REQ("OARHW010"),//old TXPDC024 new: OARHW010
    RETICLE_STORE_REQ("ODRBW016"),// old: TXPDC025 new: ODRBW016
    RETICLE_POD_XFER_REQ("OARHW016"),//old: TXPDC034 new: OARHW016
    RETICLE_DISPATCH_AND_COMPONENT_JOB_STATUS_CHANGE_REQ("OARHW009"),//old: TXPDC021 new: OARHW009
    RETICLE_STORE_RPT("ODRBR015"),// old: TXPDR018 new: ODRBR015
    RETICLE_XFER_JOB_CREATE_REQ("OARHW004"),//old: TXPDC016 new: OARHW004
    WHAT_RETICLE_ACTION_LIST_REQ("OARHW019"),//old:TXDSC015 new: OARHW019
    RETICLE_POD_XFER_JOB_CREATE_REQ("OARHW015"),//old:TXPDC033 new OARHW015
    RETICLE_POD_XFER_JOB_COMP_RPT("OARHR002"),//old: TXPDR022 new: OARHR002
    RETICLE_POD_UNLOADING_RPT("ODRBR013"),// old: TXPDR021 new: ODRBR013
    RETICLE_POD_UNCLAMP_RPT("OARHR001"),//old: TXPDR020 new: OARHR001
    RETICLE_POD_LOADING_RPT("ODRBR012"),// old: TXPDR017 new: ODRBR012
    RETICLE_POD_UNCLAMP_REQ("OARHW014"),//old: TXPDC032 new: OARHW014
    RETICLE_POD_UNCLAMP_AND_XFER_JOB_CREATE_REQ("OARHW013"),//old: TXPDC031 new: OARHW013
    BARE_RETICLE_STOCKER_INFO_INQ("ODRBQ014"),// old:TXPDQ017  new: ODRBQ014
    BARE_RETICLE_STOCKER_ONLINE_MODE_CHANGE_REQ("ODRBW008"),// old: TXPDC038 new: ODRBW008
    RETICLE_COMPONENT_JOB_LIST_INQ("OARHQ003"),//old: TXPDQ020 new: OARHQ003
    RETICLE_DISPATCH_JOB_LIST_INQ("OARHQ002"),//old: TXPDQ019 new: OARHQ002
    RETICLE_POD_INVENTORY_REQ("ODRBW012"),//old: TXPDC036 new ODRBW012
    RETICLE_POD_OFFLINE_LOADING_REQ("ODRBW013"),// old:TXPDC022  new: ODRBW013
    RETICLE_POD_OFFLINE_UNLOADING_REQ("ODRBW014"),// old:TXPDC029  new: ODRBW014
    RETICLE_POD_UNCLAMP_JOB_CREATE_REQ("OARHW012"),//old: TXPDC030 new: OARHW012
    RETICLE_INVENTORY_REQ("ODRBW009"),//old: TXPDC004 new: ODRBW009
    RETICLE_POD_XFER_JOB_DELETE_REQ("OARHW017"),//old: TXPDC035 new: OARHW017
    RETICLE_POD_XFER_JOB_LIST_INQ("OARHQ004"),//old: TXPDQ021 new： OARHQ004
    WHAT_RETICLE_POD_FOR_RETICLE_XFER_INQ("OARHQ007"),//old: TXDSQ018 new: OARHQ007

    CONSTRAINT_LIST_BY_EQP_INQ("OCONQ111"),
    CONSTRAINT_EQP_ADD_REQ("OCONW111"),
    CONSTRAINT_EQP_MODIFY_REQ("OCONW222"),
    CONSTRAINT_EQP_CANCEL_REQ("OCONW333"),
    //----------------- toolConstraint start --------------------
    CONSTRAINT_HISOTORY_LIST_INQ("OCONQ009"),
    //----------------- toolConstraint end--------------------

    LOT_SAMPLING_RULE_CHECK("LS20006"),
    WAFER_SAMPLING_RULE_SEL("SWSAQ003"),

    PILOT_RUN_STATUS_CHANGE("OPRSC111"),
    CREATE_PILOT_RUN_PLAN("OPRSC222"),
    CREATE_PILOT_RUN_JOB("OPRSC333"),
    CREATE_RECIPE_INFO("OPRSC444"),
    PILOT_RUN_CANCEL("OPRSC555"),
    PILOT_RUN_LIST("OPRSC666"),
    PILOT_RUN_JOB_INFO("OPRSC777"),

    //----------------Pilot run recipe group job----------------start
    PILOT_JOB_LIST("OPRLQ009"),
    CREATE_RECIPE_JOB("OPRLW011"),
    DELETE_RECIPE_JOB("OPRLW012"),
    RECIPE_JOB_BIND_LOT("OPRLW013"),
    //----------------Pilot run recipe group job----------------end

    //----------------Pilot run recipe group----------------start
    CREATE_PILOT_RUN_RECIPE_GROUP ("OPRLW008"),
    DELETE_PILOT_RUN_RECIPE_GROUP("OPRLW009"),
    UPDATE_PILOT_RUN_RECIPE_GROUP("OPRLW010"),
    GET_PILOT_RUN_RECIPE_GROUP("OPRLQ008"),
    GET_PILOT_RECIPE_LIST("OPRLQ010"),

    //----------------Pilot run recipe group----------------end

    //==========FSM start
    FSM_LOT_INFO_INQ("OFSMQ001"),
    FSM_LOT_DEFINITION_LIST_INQ("OFSMQ002"),
    FSM_LOT_REMOVE_REQ("OFSMW001"),
    FSM_LOT_INFO_SET_REQ("OFSMW002"),
    FSM_LOT_ACTION_REQ("OFSMW003"),
    //==========FSM end

    DEPARTMENT_AUTHORITY_SECTION_INQ("ODPTQ001"),
    DEPARTMENT_AUTHORITY_REASON_CODE_INQ("ODPTQ002"),
    DEPARTMENT_AUTHORITY_HOLD_DEPARTMENT_CHANGE_REQ("ODPTW003"),
    DEPARTMENT_AUTHORITY_FUTURE_HOLD_DEPARTMENT_CHANGE_REQ("ODPTW004"),
    DEPARTMENT_AUTHORITY_PROCESS_HOLD_DEPARTMENT_CHANGE_REQ("ODPTW005"),

    //========eqp area
    EQP_SEARCH_FOR_SETTING_EQPBOARD_INQ("OINFQ013"),
    EQP_AREA_BOARD_LIST_INQ("OINFQ014"),
    EQP_WORK_ZONE_LIST_INQ("OINFQ015"),
    EQP_BOARD_USER_BINDING_REQ("OINFW004"),
    EQP_BOARD_WORK_ZONE_BINDING_REQ("OINFW005"),
    EQP_AREA_CANCEL_USER_REQ("OINFW006"),
    EQP_AREA_CANCEL_WORK_ZONE_REQ("OINFW007"),
    EQP_AREA_MOVE_USER_REQ("OINFW008"),
    EQP_AREA_MOVE_WORK_ZONE_REQ("OINFW009"),
    //========eqp area


    OCAP_UPDATE_RPT("OOCPR001"),
    //========eqp auto move in reserve
    EQP_AUTO_MOVE_IN_RESERVE_REQ("ODISW0010"),
    //========eqp auto move in reserve

    //==========chamber level recipe
    CRCP_DESIGNATED_INQ("OCLPQ001"),
    //==========chamber level recipe

    //======fam
    FAM_SORTJOB_HISTORY_INQ("OFAMQ003"),
    SORT_JOB_HISTORY_STATUA_CHANGE_REQ("OSJHQ002"),
    FAM_AUTO_SPLITS_INQ("OFAMQ001"),
    FAM_AUTO_MERGES_INQ("OFAMQ002"),
    //======fam

    //==========layout probe
    PROBE_LIST_INQ("TXPDQ001"),
    PROBE_ID_LIST_INQ("TXPCQ022"),
    PROBE_STATUS_INQ("TXPDQ002"),
    PROBE_STOCKER_INFO_INQ("TXPDQ003"),
    PROBE_GROUP_ID_LIST_INQ("TXPCQ024"),
    PROEB_STATUS_CHANGE_RPT("TXPDR001"),
    PROBE_STATUS_MULTI_CHANGE_RPT("TXPDR009"),
    PROBE_XFER_STATUS_CHANGE_RPT("TXPDR003"),
    PROBE_USAGE_COUNT_RESET_REQ("TXPDC003"),
    //==========layout probe


    //================new Sorter
    SORT_JOB_STATUS_CHANGE_RPT("OSRTR004"), // TxSortJobStatusChangeRpt ID
    SORT_ACTION_RPT("OSRTR005"), // TxSortActionRpt ID
    LOADING_LOT_FOR_SORTER_RPT("OSRTR006"), // TxCarrierLoadingForSORRpt ID
    UN_LOADING_LOT_FOR_SORTER_RPT("OSRTR007"), // The TxCarrierUnloadingForSORRpt D
    SORT_JOB_CANCEL_RPT("OSRTR008"), // TxSJCancelRPT ID
    SORT_JOB_CREATE_REQ("OSRTW012"), // TxSJCreateReq ID
    SORT_JOB_CANCEL_REQ("OSRTW013"), // TxSJCancelReq ID
    SORT_JOB_PRIORITY_CHANGE_REQ("OSRTW014"), // TxSortJobPriorityChangeReq ID
    SORT_ACTION_REQ("OSRTW015"), // TxSortActionReq ID
    WAFER_SORTER_POSITION_ADJUST_REQ("OSRTW016"),         //  The OnlineSorterSlotmapAdjustReq Transaction ID
    WAFER_SORTER_ACTION_START_REQ("OSRTW017"), // TxSortActionStart ID
    WAFER_SORTER_ACTION_LIST_INQ("OSRTQ014"), //The TxOnlineSorterActionSelectionInq ID
    SJ_CONDITION_CHECK_REQ("OSRTW020"), // TxSJConditionCheckReq ID
    WAFER_SLOTMAP_CHANGE_REQ("OSRTW021"),
    WAFER_SORTER_DATA_COMPARE_REQ("OSRTW022"),  // TxOnlineSorterSlotmapCompareReq
    SORT_ACTION_INQ("OSRTQ012"),
    SORT_JOB_LIST_INQ("OSRTQ013"), // TxSJListInq ID
    WAFER_SORT_ACTION_REGISTER_REQ("OSRTW018"),
    SORT_SCANBAR_CODE_INQ("OSRTQ015"), // ScanbarCodeInq ID
    SORT_JOB_HISTORY_INQ("OSRTQ016"), //TXGetSortJobHistory
    CARRIER_AND_LOT_INQ("OSRTQ017"),
    CASSETTE_EXCHANGE_REQ("OSRTW002"),

    /**
     * Task-461 CarrierOutPortReq TransactionID
     */
    CARRIER_OUT_PORT_REQ("OEQPW030"),
    CARRIER_OUT_REQ("OEQPW031")
    ;
    private String value;
    TransactionIDEnum(String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }

    /**
     * description:
     * This method use to get TransactionIDEnum by value, if not found, it will return null.
     * change history:
     * date             defect#             person             comments
     * ---------------------------------------------------------------------------------------------------------------------
     *
     * @param value
     * @return com.fa.cim.constant.TransactionIDEnum
     * @author Bear
     * @date 2018/3/20
     */
    public static TransactionIDEnum get(String value) {
        if (value instanceof String) {
            for (TransactionIDEnum transactionIDEnum : TransactionIDEnum.values()) {
                if (value.equals(transactionIDEnum.getValue())) {
                    return transactionIDEnum;
                }
            }
        }
        return NULL;
    }

    /**
     * description:
     * This method use to determine whether the transactionIDEnum's value and value are equal.
     * If equal then return true,otherwise return false.
     * change history:
     * date             defect#             person             comments
     * ---------------------------------------------------------------------------------------------------------------------
     *
     * @param transactionIDEnum - transaction ID
     * @param value - value
     * @return boolean
     * @author Bear
     * @date 2018/3/20
     */
    public static boolean equals(TransactionIDEnum transactionIDEnum, String value) {
        if (value instanceof String) {
            return value.equals(transactionIDEnum.getValue());
        }
        return (null == transactionIDEnum.getValue());
    }

    public static boolean equals(String value, TransactionIDEnum transactionIDEnum) {
        return equals(transactionIDEnum, value);
    }

    /**
     * @return Return ture if the input trxID is equals instance value.
     * @param trxId transaction id
     */
    public boolean equals(String trxId) {
        return this.value.equals(trxId);
    }

    /**
     * @return Return ture if the input trxID is unequal instance value.
     * @param trxId transaction id
     */
    public boolean unEqual(String trxId) {
        return !equals(trxId);
    }

    @Override
    public String toString() {
        return this.value;
    }

}
