package com.fa.cim.constant;

import com.fa.cim.common.constant.BizConstant;

/**
 * description:
 * <p>
 * change history:
 * date             defect#             person             comments
 * ---------------------------------------------------------------------------------------------------------------------
 * 2019/11/25          ********            light                create file
 *
 * @author: light
 * @date: 2019/11/25 22:13
 * @copyright: 2019, FA Software (Shanghai) Co., Ltd. All Rights Reserved.
 */
public class HistoryInfoConstant {

    //--------------------------------Equipment---------------------------------//
    public static class EquipmentConstant {
        public static final String  MANDATORY_HASH_KEY = BizConstant.SP_HISTORYCOLUMNNAME_EQUIPMENTID;

        public static final String[][] paramKeyFHCSCHS = { { MANDATORY_HASH_KEY             , BizConstant.SP_HASHDATA_EQP_ID      },
                { BizConstant.SP_HISTORYCOLUMNNAME_CHAMBERID , BizConstant.SP_HASHDATA_PROCRSC_ID  },
                { null                           , null                    } };

        public static final String[][] paramKeyFHESCHS ={ { MANDATORY_HASH_KEY             , BizConstant.SP_HASHDATA_EQP_ID      },
                { null                           , null                    } };

        public static final String[][] paramKeyFHEMCHS ={ { MANDATORY_HASH_KEY             , BizConstant.SP_HASHDATA_EQP_ID      },
                { null                           , null                    } };

        public static final String[][] paramKeyFHOPEHS ={ { MANDATORY_HASH_KEY             , BizConstant.SP_HASHDATA_EQP_ID      },
                { BizConstant.SP_HISTORYCOLUMNNAME_RECIPEID  , BizConstant.SP_HASHDATA_RECIPE_ID   },
                { BizConstant.SP_HISTORYCOLUMNNAME_PRODUCTID , BizConstant.SP_HASHDATA_PRODSPEC_ID },
                { null                           , null                    } };
        public static final String[][] paramKeyFHEQPMONHS ={ { MANDATORY_HASH_KEY                 , BizConstant.SP_HASHDATA_EQP_ID        },
                { BizConstant.SP_HISTORYCOLUMNNAME_CHAMBERID     , BizConstant.SP_HASHDATA_CHAMBER_ID    },
                { BizConstant.SP_HISTORYCOLUMNNAME_EQPMONID      , BizConstant.SP_HASHDATA_EQPMON_ID     },
                { null                               , null                      } };

        public static final String[][] paramKeyOHSEASON ={ { MANDATORY_HASH_KEY                 , BizConstant.SP_HASHDATA_EQP_ID        },
                { BizConstant.SP_HISTORYCOLUMNNAME_SEASONID      , BizConstant.SP_HASHDATA_SEASON_ID     },
                { null                               , null                      } };

        public static final String[][] paramKeyFHEQPMONJOBHS ={ { MANDATORY_HASH_KEY                 , BizConstant.SP_HASHDATA_EQP_ID        },
                { BizConstant.SP_HISTORYCOLUMNNAME_CHAMBERID     , BizConstant.SP_HASHDATA_CHAMBER_ID    },
                { BizConstant.SP_HISTORYCOLUMNNAME_EQPMONID      , BizConstant.SP_HASHDATA_EQPMON_ID     },
                { null                               , null                      } };

        public static final String[][] paramKeyOHSEASONJOB ={ { MANDATORY_HASH_KEY                 , BizConstant.SP_HASHDATA_EQP_ID        },
                { BizConstant.SP_HISTORYCOLUMNNAME_CHAMBERID     , BizConstant.SP_HASHDATA_CHAMBER    },
                { BizConstant.SP_HISTORYCOLUMNNAME_SEASONID      , BizConstant.SP_HASHDATA_SEASON_ID     },
                { null                               , null                      } };

        public static final String[][] paramKeyFHBUFFRSCCHS ={ { MANDATORY_HASH_KEY , BizConstant.SP_HASHDATA_EQP_ID      },
                { null                    , null                    } };

        public static final String[][] paramKeyFHEQPPORTSCHS ={ { MANDATORY_HASH_KEY    , BizConstant.SP_HASHDATA_EQP_ID      },
                { BizConstant.SP_HISTORYCOLUMNNAME_PORTID , BizConstant.SP_HASHDATA_PORT_ID     },
                { null                        , null                    } };

        public static final int SELECT_ITEM_MAX = 57;

        public static final String[][] selectItemFHCSCHS = { { BizConstant.SP_HASHDATA_EVENT_CREATE_TIME  , BizConstant.SP_HISTORYCOLUMNNAME_REPORTTIMESTAMP             },
                { "'OHCMBSC' as HistoryName"                    , BizConstant.SP_HISTORYCOLUMNNAME_HISTORYNAME                 },
                { "'' as PortID"                           , null                                             },
                { BizConstant.SP_HASHDATA_PROCRSC_ID + " as ChamberID"        , BizConstant.SP_HISTORYCOLUMNNAME_CHAMBERID                   },
                { "'' as OperationCategory"                           , null                                             },
                { "'' as OperationMode"                           , null                                             },
                { "'' as LogicalRecipeID"                           , null                                             },
                { "'' as MachineRecipeID"                           , null                                             },
                { "'' as PhysicalRecipeID"                           , null                                             },
                { "'' as ControlJobID"                           , null                                             },
                { BizConstant.SP_HASHDATA_E10_STATE + " as E10Status"         , BizConstant.SP_HISTORYCOLUMNNAME_E10STATUS                   },
                { "'' as EquipmentStatus"                           , null                                             },
                { BizConstant.SP_HASHDATA_PR_STATE + " as ChamberStatus"          , BizConstant.SP_HISTORYCOLUMNNAME_CHAMBERSTATUS               },
                { BizConstant.SP_HASHDATA_NEW_E10_STATE + " as New_E10Status"     , BizConstant.SP_HISTORYCOLUMNNAME_NEWE10STATUS                },
                { "'' as New_EquipmentStatus"                           , null                                             },
                { BizConstant.SP_HASHDATA_NEW_CHAMBER_STATE + " as New_ChamberStatus" , BizConstant.SP_HISTORYCOLUMNNAME_NEWCHAMBERSTATUS            },
                { BizConstant.SP_HASHDATA_ACT_E10_STATE + " as TCS_Report_E10Status"     , BizConstant.SP_HISTORYCOLUMNNAME_TCSREPORTE10STATUS          },
                { "'' as TCS_Report_EquipmentStatus"                           , null                                             },
                { BizConstant.SP_HASHDATA_ACT_CHAMBER_STATE + " as TCS_Report_ChamberStatus" , BizConstant.SP_HISTORYCOLUMNNAME_TCSREPORTCHAMBERSTATUS      },
                { BizConstant.SP_HASHDATA_NEW_ACT_E10_STATE + " as TCS_Report_New_E10Status" , BizConstant.SP_HISTORYCOLUMNNAME_TCSREPORTNEWE10STATUS       },
                { "'' as TCS_Report_New_EquipmentStatus"                           , null                                             },
                { BizConstant.SP_HASHDATA_NEW_ACT_CHMBR_ST + " as TCS_Report_New_ChamberStatus"  , BizConstant.SP_HISTORYCOLUMNNAME_TCSREPORTNEWCHAMBERSTATUS   },
                { "'' as Equipment_OperationMode"                           , null                                             },
                { "'' as New_Equipment_OperationMode"                           , null                                             },
                { BizConstant.SP_HASHDATA_START_TIME  + " as Status_Mode_StartedTime"       , BizConstant.SP_HISTORYCOLUMNNAME_STATUSMODESTARTEDTIME       },
                { BizConstant.SP_HASHDATA_START_SHOP_DATE + " as Status_Mode_Started_ShopDate"   , BizConstant.SP_HISTORYCOLUMNNAME_STATUSMODESTARTEDSHOPDATE   },
                { BizConstant.SP_HASHDATA_END_TIME + " as Status_Mode_EndedTime"          , BizConstant.SP_HISTORYCOLUMNNAME_STATUSMODEENDEDTIME         },
                { BizConstant.SP_HASHDATA_END_SHOP_DATE + " as Status_Mode_EndedShopDate"     , BizConstant.SP_HISTORYCOLUMNNAME_STATUSMODEENDEDSHOPDATE     },
                { "'' as Port_OperationMode"                           , null                                             },
                { "'' as Port_OnlineMode"                           , null                                             },
                { "'' as Port_DispatchMode"                           , null                                             },
                { "'' as Port_AccessMode"                           , null                                             },
                { "'' as Port_Operation_StartMode"                           , null                                             },
                { "'' as Port_Operation_CompletionMode"                           , null                                             },
                { "'' as Description_of_OperationMode"                           , null                                             },
                { "'' as Eqp_MonitorID"                           , null                                             },
                { "'' as Eqp_MonitorType"                           , null                                             },
                { "'' as Eqp_MonitorStatus"                           , null                                             },
                { "'' as Prev_Eqp_MonitorStatus"                           , null                                             },
                { "'' as Eqp_MonitorJobID"                           , null                                             },
                { "'' as Eqp_MonitorJobStatus"                           , null                                             },
                { "'' as Prev_Eqp_MonitorJobStatus"                           , null                                             },
                { "0 as RetryCount"                            , null                                             },
                { "'' as BufferRscCategory"                           , null                                             },
                { "0 as SM_Capacity"                            , null                                             },
                { "0 as Dynamic_Capacity"                            , null                                             },
                { "'' as PortType"                           , null                                             },
                { "'' as PortUsage"                           , null                                             },
                { "'' as PortState"                           , null                                             },
                { "'' as DispatchedState"                           , null                                             },
                { "TO_TIMESTAMP('1901-01-01-00.00.00.000000','yyyy-mm-dd hh24:mi:ss.ff') as DispatchedTime" , null                                             },
                { "'' as Dispatched_DulableID"                           , null                                             },
                { "TO_TIMESTAMP('1901-01-01-00.00.00.000000','yyyy-mm-dd hh24:mi:ss.ff') as ClaimedTime" , null                                             },
                { "0 as ClaimedShopDate"                            , null                                             },
                { BizConstant.SP_HASHDATA_CLAIM_USER_ID      , BizConstant.SP_HISTORYCOLUMNNAME_USERID                      },
                { BizConstant.SP_HASHDATA_CLAIM_MEMO         , BizConstant.SP_HISTORYCOLUMNNAME_CLAIMMEMO                   },
                { BizConstant.SP_HASHDATA_STORE_TIME         , BizConstant.SP_HISTORYCOLUMNNAME_STOREDTIMESTAMP             }
        };

        public static final String[][] selectItemFHESCHS = { { BizConstant.SP_HASHDATA_EVENT_CREATE_TIME  , BizConstant.SP_HISTORYCOLUMNNAME_REPORTTIMESTAMP             },
                { "'OHEQSC' as HistoryName"                    , BizConstant.SP_HISTORYCOLUMNNAME_HISTORYNAME                 },
                { "'' as PortID"                           , null                                             },
                { "'' as ChamberID"                           , null                                             },
                { "'' as OperationCategory"                           , null                                             },
                { "'' as OperationMode"                           , null                                             },
                { "'' as LogicalRecipeID"                           , null                                             },
                { "'' as MachineRecipeID"                           , null                                             },
                { "'' as PhysicalRecipeID"                           , null                                             },
                { "'' as ControlJobID"                           , null                                             },
                { BizConstant.SP_HASHDATA_E10_STATE + " as E10Status"         , BizConstant.SP_HISTORYCOLUMNNAME_E10STATUS                   },
                { BizConstant.SP_HASHDATA_EQP_STATE + " as EquipmentStatus"         , BizConstant.SP_HISTORYCOLUMNNAME_EQUIPMENTSTATUS             },
                { "'' as ChamberStatus"                           , null                                             },
                { BizConstant.SP_HASHDATA_NEW_E10_STATE + " as New_E10Status"     , BizConstant.SP_HISTORYCOLUMNNAME_NEWE10STATUS                },
                { BizConstant.SP_HASHDATA_NEW_EQPMENT_STATE + " as New_EquipmentStatus" , BizConstant.SP_HISTORYCOLUMNNAME_NEWEQUIPMENTSTATUS          },
                { "'' as New_ChamberStatus"                           , null                                             },
                { BizConstant.SP_HASHDATA_ACT_E10_STATE + " as TCS_Report_E10Status"     , BizConstant.SP_HISTORYCOLUMNNAME_TCSREPORTE10STATUS          },
                { BizConstant.SP_HASHDATA_ACT_EUIPMENT_STATE + " as TCS_Report_EquipmentStatus", BizConstant.SP_HISTORYCOLUMNNAME_TCSREPORTEQUIPMENTSTATUS    },
                { "'' as TCS_Report_ChamberStatus"                           , null                                             },
                { BizConstant.SP_HASHDATA_NEW_ACT_E10_STATE + " as TCS_Report_New_E10Status" , BizConstant.SP_HISTORYCOLUMNNAME_TCSREPORTNEWE10STATUS       },
                { BizConstant.SP_HASHDATA_NEW_ACT_EQPMENT_ST + " as TCS_Report_New_EquipmentStatus", BizConstant.SP_HISTORYCOLUMNNAME_TCSREPORTNEWEQUIPMENTSTATUS },
                { "'' as TCS_Report_New_ChamberStatus"                           , null                                             },
                { BizConstant.SP_HASHDATA_OPE_MODE + " as Equipment_OperationMode"          , BizConstant.SP_HISTORYCOLUMNNAME_EQUIPMENTOPERATIONMODE      },
                { BizConstant.SP_HASHDATA_NEW_EQP_OPE_MODE + " as New_Equipment_OperationMode"  , BizConstant.SP_HISTORYCOLUMNNAME_NEWEQUIPMENTOPERATIONMODE   },
                { BizConstant.SP_HASHDATA_START_TIME + " as Status_Mode_StartedTime"        , BizConstant.SP_HISTORYCOLUMNNAME_STATUSMODESTARTEDTIME       },
                { BizConstant.SP_HASHDATA_START_SHOP_DATE + " as Status_Mode_Started_ShopDate"   , BizConstant.SP_HISTORYCOLUMNNAME_STATUSMODESTARTEDSHOPDATE   },
                { BizConstant.SP_HASHDATA_END_TIME + " as Status_Mode_EndedTime"          , BizConstant.SP_HISTORYCOLUMNNAME_STATUSMODEENDEDTIME         },
                { BizConstant.SP_HASHDATA_END_SHOP_DATE + " as Status_Mode_EndedShopDate"     , BizConstant.SP_HISTORYCOLUMNNAME_STATUSMODEENDEDSHOPDATE     },
                { "'' as Port_OperationMode"                           , null                                             },
                { "'' as Port_OnlineMode"                           , null                                             },
                { "'' as Port_DispatchMode"                           , null                                             },
                { "'' as Port_AccessMode"                           , null                                             },
                { "'' as Port_Operation_StartMode"                           , null                                             },
                { "'' as Port_Operation_CompletionMode"                           , null                                             },
                { "'' as Description_of_OperationMode"                           , null                                             },
                { "'' as Eqp_MonitorID"                           , null                                             },
                { "'' as Eqp_MonitorType"                           , null                                             },
                { "'' as Eqp_MonitorStatus"                           , null                                             },
                { "'' as Prev_Eqp_MonitorStatus"                           , null                                             },
                { "'' as Eqp_MonitorJobID"                           , null                                             },
                { "'' as Eqp_MonitorJobStatus"                           , null                                             },
                { "'' as Prev_Eqp_MonitorJobStatus"                           , null                                             },
                { "0 as RetryCount"                            , null                                             },
                { "'' as BufferRscCategory"                           , null                                             },
                { "0 as SM_Capacity"                            , null                                             },
                { "0 as Dynamic_Capacity"                            , null                                             },
                { "'' as PortType"                           , null                                             },
                { "'' as PortUsage"                           , null                                             },
                { "'' as PortState"                           , null                                             },
                { "'' as DispatchedState"                           , null                                             },
                { "TO_TIMESTAMP('1901-01-01-00.00.00.000000','yyyy-mm-dd hh24:mi:ss.ff') as DispatchedTime" , null                                             },
                { "'' as Dispatched_DulableID"                           , null                                             },
                { "TO_TIMESTAMP('1901-01-01-00.00.00.000000','yyyy-mm-dd hh24:mi:ss.ff') as ClaimedTime" , null                                             },
                { "0 as ClaimedShopDate"                            , null                                             },
                { BizConstant.SP_HASHDATA_CLAIM_USER_ID      , BizConstant.SP_HISTORYCOLUMNNAME_USERID                      },
                { BizConstant.SP_HASHDATA_CLAIM_MEMO         , BizConstant.SP_HISTORYCOLUMNNAME_CLAIMMEMO                   },
                { BizConstant.SP_HASHDATA_STORE_TIME         , BizConstant.SP_HISTORYCOLUMNNAME_STOREDTIMESTAMP             }
        };

        public static final String[][] selectItemFHEMCHS = { { BizConstant.SP_HASHDATA_EVENT_CREATE_TIME  , BizConstant.SP_HISTORYCOLUMNNAME_REPORTTIMESTAMP             },    // Report Time Stamp//DSN000096173
                { "'OHEQPMODECHG' as HistoryName"                    , BizConstant.SP_HISTORYCOLUMNNAME_HISTORYNAME                 },
                { BizConstant.SP_HASHDATA_PORT_ID            , BizConstant.SP_HISTORYCOLUMNNAME_PORTID                      },
                { "'' as ChamberID"                           , null                                             },
                { "'' as OperationCategory"                           , null                                             },
                { "'' as OperationMode"                           , null                                             },
                { "'' as LogicalRecipeID"                           , null                                             },
                { "'' as MachineRecipeID"                           , null                                             },
                { "'' as PhysicalRecipeID"                           , null                                             },
                { "'' as ControlJobID"                           , null                                             },
                { "'' as E10Status"                           , null                                             },
                { "'' as EquipmentStatus"                           , null                                             },
                { "'' as ChamberStatus"                           , null                                             },
                { "'' as New_E10Status"                           , null                                             },
                { "'' as New_EquipmentStatus"                           , null                                             },
                { "'' as New_ChamberStatus"                           , null                                             },
                { "'' as TCS_Report_E10Status"                           , null                                             },
                { "'' as TCS_Report_EquipmentStatus"                           , null                                             },
                { "'' as TCS_Report_ChamberStatus"                           , null                                             },
                { "'' as TCS_Report_New_E10Status"                           , null                                             },
                { "'' as TCS_Report_New_EquipmentStatus"                           , null                                             },
                { "'' as TCS_Report_New_ChamberStatus"                           , null                                             },
                { "'' as Equipment_OperationMode"                           , null                                             },
                { "'' as New_Equipment_OperationMode"                           , null                                             },
                { "TO_TIMESTAMP('1901-01-01-00.00.00.000000','yyyy-mm-dd hh24:mi:ss.ff') as Status_Mode_StartedTime" , null                                             },
                { "0 as Status_Mode_Started_ShopDate"                            , null                                             },
                { "TO_TIMESTAMP('1901-01-01-00.00.00.000000','yyyy-mm-dd hh24:mi:ss.ff') as Status_Mode_EndedTime" , null                                             },
                { "0 as Status_Mode_EndedShopDate"                            , null                                             },
                { BizConstant.SP_HASHDATA_OPE_MODE + " as Port_OperationMode"           , BizConstant.SP_HISTORYCOLUMNNAME_PORTOPERATIONMODE           },
                { BizConstant.SP_HASHDATA_ONLINE_MODE + " as Port_OnlineMode"       , BizConstant.SP_HISTORYCOLUMNNAME_PORTONLINEMODE              },
                { BizConstant.SP_HASHDATA_DISP_MODE + " as Port_DispatchMode"         , BizConstant.SP_HISTORYCOLUMNNAME_PORTDISPATCHMODE            },
                { BizConstant.SP_HASHDATA_ACCESS_MODE  + " as Port_AccessMode"      , BizConstant.SP_HISTORYCOLUMNNAME_PORTACCESSMODE              },
                { BizConstant.SP_HASHDATA_OPE_START_MODE + " as Port_Operation_StartMode"    , BizConstant.SP_HISTORYCOLUMNNAME_PORTOPERATIONSTARTMODE      },
                { BizConstant.SP_HASHDATA_OPE_COMP_MODE + " as Port_Operation_CompletionMode"     , BizConstant.SP_HISTORYCOLUMNNAME_PORTOPERATIONCOMPLETIONMODE },
                { BizConstant.SP_HASHDATA_DESCRIPTION + " as Description_of_OperationMode"       , BizConstant.SP_HISTORYCOLUMNNAME_DESCRIPTIONOFOPERATIONMODE  },
                { "'' as Eqp_MonitorID"                           , null                                             },
                { "'' as Eqp_MonitorType"                           , null                                             },
                { "'' as Eqp_MonitorStatus"                           , null                                             },
                { "'' as Prev_Eqp_MonitorStatus"                           , null                                             },
                { "'' as Eqp_MonitorJobID"                           , null                                             },
                { "'' as Eqp_MonitorJobStatus"                           , null                                             },
                { "'' as Prev_Eqp_MonitorJobStatus"                           , null                                             },
                { "0 as RetryCount"                            , null                                             },
                { "'' as BufferRscCategory"                           , null                                             },
                { "0 as SM_Capacity"                            , null                                             },
                { "0 as Dynamic_Capacity"                            , null                                             },
                { "'' as PortType"                           , null                                             },
                { "'' as PortUsage"                           , null                                             },
                { "'' as PortState"                           , null                                             },
                { "'' as DispatchedState"                           , null                                             },
                { "TO_TIMESTAMP('1901-01-01-00.00.00.000000','yyyy-mm-dd hh24:mi:ss.ff') as DispatchedTime" , null                                             },
                { "'' as Dispatched_DulableID"                           , null                                             },
                { BizConstant.SP_HASHDATA_CLAIM_TIME + " as ClaimedTime"        , BizConstant.SP_HISTORYCOLUMNNAME_CLAIMEDTIME                 },
                { BizConstant.SP_HASHDATA_CLAIM_SHOP_DATE + " as ClaimedShopDate"   , BizConstant.SP_HISTORYCOLUMNNAME_CLAIMEDSHOPDATE             },
                { BizConstant.SP_HASHDATA_CLAIM_USER_ID      , BizConstant.SP_HISTORYCOLUMNNAME_USERID                      },
                { BizConstant.SP_HASHDATA_CLAIM_MEMO         , BizConstant.SP_HISTORYCOLUMNNAME_CLAIMMEMO                   },
                { BizConstant.SP_HASHDATA_STORE_TIME         , BizConstant.SP_HISTORYCOLUMNNAME_STOREDTIMESTAMP             }
        };

        public static final String[][] selectItemFHOPEHS = { { BizConstant.SP_HASHDATA_EVENT_CREATE_TIME  , BizConstant.SP_HISTORYCOLUMNNAME_REPORTTIMESTAMP             },
                { "'OHLOTOPE' as HistoryName"                    , BizConstant.SP_HISTORYCOLUMNNAME_HISTORYNAME                 },
                { "'' as PortID"                           , null                                             },
                { "'' as ChamberID"                           , null                                             },
                { BizConstant.SP_HASHDATA_OPE_CATEGORY + " as OperationCategory"      , BizConstant.SP_HISTORYCOLUMNNAME_OPERATIONCATEGORY           },
                { BizConstant.SP_HASHDATA_OPE_MODE + " as OperationMode"          , BizConstant.SP_HISTORYCOLUMNNAME_OPERATIONMODE               },
                { BizConstant.SP_HASHDATA_LC_RECIPE_ID + " as LogicalRecipeID"      , BizConstant.SP_HISTORYCOLUMNNAME_LOGICALRECIPEID             },
                { BizConstant.SP_HASHDATA_RECIPE_ID + " as MachineRecipeID"         , BizConstant.SP_HISTORYCOLUMNNAME_MACHINERECIPEID             },
                { BizConstant.SP_HASHDATA_PH_RECIPE_ID + " as PhysicalRecipeID"      , BizConstant.SP_HISTORYCOLUMNNAME_PHYSICALRECIPEID            },
                { BizConstant.SP_HASHDATA_CTRL_JOB + " as ControlJobID"          , BizConstant.SP_HISTORYCOLUMNNAME_CONTROLJOBID                },
                { "'' as E10Status"                           , null                                             },
                { "'' as EquipmentStatus"                           , null                                             },
                { "'' as ChamberStatus"                           , null                                             },
                { "'' as New_E10Status"                           , null                                             },
                { "'' as New_EquipmentStatus"                           , null                                             },
                { "'' as New_ChamberStatus"                           , null                                             },
                { "'' as TCS_Report_E10Status"                           , null                                             },
                { "'' as TCS_Report_EquipmentStatus"                           , null                                             },
                { "'' as TCS_Report_ChamberStatus"                           , null                                             },
                { "'' as TCS_Report_New_E10Status"                           , null                                             },
                { "'' as TCS_Report_New_EquipmentStatus"                           , null                                             },
                { "'' as TCS_Report_New_ChamberStatus"                           , null                                             },
                { "'' as Equipment_OperationMode"                           , null                                             },
                { "'' as New_Equipment_OperationMode"                           , null                                             },
                { "TO_TIMESTAMP('1901-01-01-00.00.00.000000','yyyy-mm-dd hh24:mi:ss.ff') as Status_Mode_StartedTime" , null                                             },
                { "0 as Status_Mode_Started_ShopDate"                            , null                                             },
                { "TO_TIMESTAMP('1901-01-01-00.00.00.000000','yyyy-mm-dd hh24:mi:ss.ff') as Status_Mode_EndedTime" , null                                             },
                { "0 as Status_Mode_EndedShopDate"                            , null                                             },
                { "'' as Port_OperationMode"                           , null                                             },
                { "'' as Port_OnlineMode"                           , null                                             },
                { "'' as Port_DispatchMode"                           , null                                             },
                { "'' as Port_AccessMode"                           , null                                             },
                { "'' as Port_Operation_StartMode"                           , null                                             },
                { "'' as Port_Operation_CompletionMode"                           , null                                             },
                { "'' as Description_of_OperationMode"                           , null                                             },
                { "'' as Eqp_MonitorID"                           , null                                             },
                { "'' as Eqp_MonitorType"                           , null                                             },
                { "'' as Eqp_MonitorStatus"                           , null                                             },
                { "'' as Prev_Eqp_MonitorStatus"                           , null                                             },
                { "'' as Eqp_MonitorJobID"                           , null                                             },
                { "'' as Eqp_MonitorJobStatus"                           , null                                             },
                { "'' as Prev_Eqp_MonitorJobStatus"                           , null                                             },
                { "0 as RetryCount"                            , null                                             },
                { "'' as BufferRscCategory"                           , null                                             },
                { "0 as SM_Capacity"                            , null                                             },
                { "0 as Dynamic_Capacity"                            , null                                             },
                { "'' as PortType"                           , null                                             },
                { "'' as PortUsage"                           , null                                             },
                { "'' as PortState"                           , null                                             },
                { "'' as DispatchedState"                           , null                                             },
                { "TO_TIMESTAMP('1901-01-01-00.00.00.000000','yyyy-mm-dd hh24:mi:ss.ff') as DispatchedTime" , null                                             },
                { "'' as Dispatched_DulableID"                           , null                                             },
                { "TO_TIMESTAMP('1901-01-01-00.00.00.000000','yyyy-mm-dd hh24:mi:ss.ff') as ClaimedTime" , null                                             },
                { "0 as ClaimedShopDate"                            , null                                             },
                { BizConstant.SP_HASHDATA_CLAIM_USER_ID      , BizConstant.SP_HISTORYCOLUMNNAME_USERID                      },
                { BizConstant.SP_HASHDATA_CLAIM_MEMO         , BizConstant.SP_HISTORYCOLUMNNAME_CLAIMMEMO                   },
                { BizConstant.SP_HASHDATA_STORE_TIME         , BizConstant.SP_HISTORYCOLUMNNAME_STOREDTIMESTAMP             }
        };

        public static final String[][] selectItemFHEQPMONHS = { { BizConstant.SP_HASHDATA_EVENT_CREATE_TIME  , BizConstant.SP_HISTORYCOLUMNNAME_REPORTTIMESTAMP          },
                { "'OHADCLOT' as HistoryName"                    , BizConstant.SP_HISTORYCOLUMNNAME_HISTORYNAME              },
                { "'' as PortID"                           , null                                             },
                { BizConstant.SP_HASHDATA_CHAMBER_ID + " as ChamberID"        , BizConstant.SP_HISTORYCOLUMNNAME_CHAMBERID                   },
                { BizConstant.SP_HASHDATA_OPE_CATEGORY + " as OperationCategory"      , BizConstant.SP_HISTORYCOLUMNNAME_OPERATIONCATEGORY           },
                { "'' as OperationMode"                           , null                                             },
                { "'' as LogicalRecipeID"                           , null                                             },
                { "'' as MachineRecipeID"                           , null                                             },
                { "'' as PhysicalRecipeID"                           , null                                             },
                { "'' as ControlJobID"                           , null                                             },
                { "'' as E10Status"                           , null                                             },
                { "'' as EquipmentStatus"                           , null                                             },
                { "'' as ChamberStatus"                           , null                                             },
                { "'' as New_E10Status"                           , null                                             },
                { "'' as New_EquipmentStatus"                           , null                                             },
                { "'' as New_ChamberStatus"                           , null                                             },
                { "'' as TCS_Report_E10Status"                           , null                                             },
                { "'' as TCS_Report_EquipmentStatus"                           , null                                             },
                { "'' as TCS_Report_ChamberStatus"                           , null                                             },
                { "'' as TCS_Report_New_E10Status"                           , null                                             },
                { "'' as TCS_Report_New_EquipmentStatus"                           , null                                             },
                { "'' as TCS_Report_New_ChamberStatus"                           , null                                             },
                { "'' as Equipment_OperationMode"                           , null                                             },
                { "'' as New_Equipment_OperationMode"                           , null                                             },
                { "TO_TIMESTAMP('1901-01-01-00.00.00.000000','yyyy-mm-dd hh24:mi:ss.ff') as Status_Mode_StartedTime" , null                                             },
                { "0 as Status_Mode_Started_ShopDate"                            , null                                             },
                { "TO_TIMESTAMP('1901-01-01-00.00.00.000000','yyyy-mm-dd hh24:mi:ss.ff') as Status_Mode_EndedTime" , null                                             },
                { "0 as Status_Mode_EndedShopDate"                            , null                                             },
                { "'' as Port_OperationMode"                           , null                                             },
                { "'' as Port_OnlineMode"                           , null                                             },
                { "'' as Port_DispatchMode"                           , null                                             },
                { "'' as Port_AccessMode"                           , null                                             },
                { "'' as Port_Operation_StartMode"                           , null                                             },
                { "'' as Port_Operation_CompletionMode"                           , null                                             },
                { "'' as Description_of_OperationMode"                           , null                                             },
                { BizConstant.SP_HASHDATA_EQPMON_ID + " as Eqp_MonitorID"         , BizConstant.SP_HISTORYCOLUMNNAME_EQPMONID                    },
                { BizConstant.SP_HASHDATA_MONITOR_TYPE + " as Eqp_MonitorType"      , BizConstant.SP_HISTORYCOLUMNNAME_MONITORTYPE                 },
                { BizConstant.SP_HASHDATA_MON_STATUS + " as Eqp_MonitorStatus"        , BizConstant.SP_HISTORYCOLUMNNAME_MONSTATUS                   },
                { BizConstant.SP_HASHDATA_PREV_MON_STATUS + " as Prev_Eqp_MonitorStatus"   , BizConstant.SP_HISTORYCOLUMNNAME_PREVMONSTATUS               },
                { "'' as Eqp_MonitorJobID"                           , null                                             },
                { "'' as Eqp_MonitorJobStatus"                           , null                                             },
                { "'' as Prev_Eqp_MonitorJobStatus"                           , null                                             },
                { "0 as RetryCount"                            , null                                             },
                { "'' as BufferRscCategory"                           , null                                             },
                { "0 as SM_Capacity"                            , null                                             },
                { "0 as Dynamic_Capacity"                            , null                                             },
                { "'' as PortType"                           , null                                             },
                { "'' as PortUsage"                           , null                                             },
                { "'' as PortState"                           , null                                             },
                { "'' as DispatchedState"                           , null                                             },
                { "TO_TIMESTAMP('1901-01-01-00.00.00.000000','yyyy-mm-dd hh24:mi:ss.ff') as DispatchedTime" , null                                             },
                { "'' as Dispatched_DulableID"                           , null                                             },
                { "TO_TIMESTAMP('1901-01-01-00.00.00.000000','yyyy-mm-dd hh24:mi:ss.ff') as ClaimedTime" , null                                             },
                { "0 as ClaimedShopDate"                            , null                                             },
                { BizConstant.SP_HASHDATA_CLAIM_USER_ID      , BizConstant.SP_HISTORYCOLUMNNAME_USERID                      },
                { BizConstant.SP_HASHDATA_CLAIM_MEMO         , BizConstant.SP_HISTORYCOLUMNNAME_CLAIMMEMO                   },
                { BizConstant.SP_HASHDATA_STORE_TIME         , BizConstant.SP_HISTORYCOLUMNNAME_STOREDTIMESTAMP             }
        };

        public static final String[][] selectItemOHSEASON = { { BizConstant.SP_HASHDATA_EVENT_CREATE_TIME  , BizConstant.SP_HISTORYCOLUMNNAME_REPORTTIMESTAMP          },
                { "'OHSEASON' as HistoryName"                    , BizConstant.SP_HISTORYCOLUMNNAME_HISTORYNAME              },
                { "'' as PortID"                           , null                                             },
                { "'' as ChamberID"        , null                   },
                { BizConstant.SP_HASHDATA_OPE_CATEGORY + " as OperationCategory"      , BizConstant.SP_HISTORYCOLUMNNAME_OPERATIONCATEGORY           },
                { "'' as OperationMode"                           , null                                             },
                { "'' as LogicalRecipeID"                           , null                                             },
                { "'' as MachineRecipeID"                           , null                                             },
                { "'' as PhysicalRecipeID"                           , null                                             },
                { "'' as ControlJobID"                           , null                                             },
                { "'' as E10Status"                           , null                                             },
                { "'' as EquipmentStatus"                           , null                                             },
                { "'' as ChamberStatus"                           , null                                             },
                { "'' as New_E10Status"                           , null                                             },
                { "'' as New_EquipmentStatus"                           , null                                             },
                { "'' as New_ChamberStatus"                           , null                                             },
                { "'' as TCS_Report_E10Status"                           , null                                             },
                { "'' as TCS_Report_EquipmentStatus"                           , null                                             },
                { "'' as TCS_Report_ChamberStatus"                           , null                                             },
                { "'' as TCS_Report_New_E10Status"                           , null                                             },
                { "'' as TCS_Report_New_EquipmentStatus"                           , null                                             },
                { "'' as TCS_Report_New_ChamberStatus"                           , null                                             },
                { "'' as Equipment_OperationMode"                           , null                                             },
                { "'' as New_Equipment_OperationMode"                           , null                                             },
                { "TO_TIMESTAMP('1901-01-01-00.00.00.000000','yyyy-mm-dd hh24:mi:ss.ff') as Status_Mode_StartedTime" , null                                             },
                { "0 as Status_Mode_Started_ShopDate"                            , null                                             },
                { "TO_TIMESTAMP('1901-01-01-00.00.00.000000','yyyy-mm-dd hh24:mi:ss.ff') as Status_Mode_EndedTime" , null                                             },
                { "0 as Status_Mode_EndedShopDate"                            , null                                             },
                { "'' as Port_OperationMode"                           , null                                             },
                { "'' as Port_OnlineMode"                           , null                                             },
                { "'' as Port_DispatchMode"                           , null                                             },
                { "'' as Port_AccessMode"                           , null                                             },
                { "'' as Port_Operation_StartMode"                           , null                                             },
                { "'' as Port_Operation_CompletionMode"                           , null                                             },
                { "'' as Description_of_OperationMode"                           , null                                             },
                { BizConstant.SP_HASHDATA_SEASON_ID + " as Season_ID"         , BizConstant.SP_HISTORYCOLUMNNAME_SEASONID                    },
                { BizConstant.SP_HASHDATA_SEASON_TYPE + " as Eqp_SeasonType"      , BizConstant.SP_HISTORYCOLUMNNAME_SEASONTYPE                 },
                { BizConstant.SP_HASHDATA_SEASON_STATUS + " as Eqp_SeasonStatus"        , BizConstant.SP_HISTORYCOLUMNNAME_SEASONSTATUS                   },
                { "'' as Prev_Eqp_MonitorStatus"   , null              },
                { "'' as Eqp_MonitorJobID"                           , null                                             },
                { "'' as Eqp_MonitorJobStatus"                           , null                                             },
                { "'' as Prev_Eqp_MonitorJobStatus"                           , null                                             },
                { "0 as RetryCount"                            , null                                             },
                { "'' as BufferRscCategory"                           , null                                             },
                { "0 as SM_Capacity"                            , null                                             },
                { "0 as Dynamic_Capacity"                            , null                                             },
                { "'' as PortType"                           , null                                             },
                { "'' as PortUsage"                           , null                                             },
                { "'' as PortState"                           , null                                             },
                { "'' as DispatchedState"                           , null                                             },
                { "TO_TIMESTAMP('1901-01-01-00.00.00.000000','yyyy-mm-dd hh24:mi:ss.ff') as DispatchedTime" , null                                             },
                { "'' as Dispatched_DulableID"                           , null                                             },
                { "TO_TIMESTAMP('1901-01-01-00.00.00.000000','yyyy-mm-dd hh24:mi:ss.ff') as ClaimedTime" , null                                             },
                { "0 as ClaimedShopDate"                            , null                                             },
                { BizConstant.SP_HASHDATA_CLAIM_USER_ID      , BizConstant.SP_HISTORYCOLUMNNAME_USERID                      },
                { BizConstant.SP_HASHDATA_CLAIM_MEMO         , BizConstant.SP_HISTORYCOLUMNNAME_CLAIMMEMO                   },
                { "TO_TIMESTAMP('1901-01-01-00.00.00.000000','yyyy-mm-dd hh24:mi:ss.ff') as StoreTime"         , null            }
        };

        public static final String[][] selectItemFHEQPMONJOBHS = { { BizConstant.SP_HASHDATA_EVENT_CREATE_TIME  , BizConstant.SP_HISTORYCOLUMNNAME_REPORTTIMESTAMP       },
                { "'OHAMONJOB' as HistoryName"                    , BizConstant.SP_HISTORYCOLUMNNAME_HISTORYNAME           },
                { "'' as PortID"                           , null                                             },
                { BizConstant.SP_HASHDATA_CHAMBER_ID +" as ChamberID"        , BizConstant.SP_HISTORYCOLUMNNAME_CHAMBERID                   },
                { BizConstant.SP_HASHDATA_OPE_CATEGORY +" as OperationCategory"     , BizConstant.SP_HISTORYCOLUMNNAME_OPERATIONCATEGORY           },
                { "'' as OperationMode"                           , null                                             },
                { "'' as LogicalRecipeID"                           , null                                             },
                { "'' as MachineRecipeID"                           , null                                             },
                { "'' as PhysicalRecipeID"                           , null                                             },
                { "'' as ControlJobID"                           , null                                             },
                { "'' as E10Status"                           , null                                             },
                { "'' as EquipmentStatus"                           , null                                             },
                { "'' as ChamberStatus"                           , null                                             },
                { "'' as New_E10Status"                           , null                                             },
                { "'' as New_EquipmentStatus"                           , null                                             },
                { "'' as New_ChamberStatus"                           , null                                             },
                { "'' as TCS_Report_E10Status"                           , null                                             },
                { "'' as TCS_Report_EquipmentStatus"                           , null                                             },
                { "'' as TCS_Report_ChamberStatus"                           , null                                             },
                { "'' as TCS_Report_New_E10Status"                           , null                                             },
                { "'' as TCS_Report_New_EquipmentStatus"                           , null                                             },
                { "'' as TCS_Report_New_ChamberStatus"                           , null                                             },
                { "'' as Equipment_OperationMode"                           , null                                             },
                { "'' as New_Equipment_OperationMode"                           , null                                             },
                { "TO_TIMESTAMP('1901-01-01-00.00.00.000000','yyyy-mm-dd hh24:mi:ss.ff') as Status_Mode_StartedTime" , null                                             },
                { "0 as Status_Mode_Started_ShopDate"                            , null                                             },
                { "TO_TIMESTAMP('1901-01-01-00.00.00.000000','yyyy-mm-dd hh24:mi:ss.ff') as Status_Mode_EndedTime" , null                                             },
                { "0 as Status_Mode_EndedShopDate"                            , null                                             },
                { "'' as Port_OperationMode"                           , null                                             },
                { "'' as Port_OnlineMode"                           , null                                             },
                { "'' as Port_DispatchMode"                           , null                                             },
                { "'' as Port_AccessMode"                           , null                                             },
                { "'' as Port_Operation_StartMode"                           , null                                             },
                { "'' as Port_Operation_CompletionMode"                           , null                                             },
                { "'' as Description_of_OperationMode"                           , null                                             },
                { BizConstant.SP_HASHDATA_EQPMON_ID + " as Eqp_MonitorID"         , BizConstant.SP_HISTORYCOLUMNNAME_EQPMONID                    },
                { "'' as Eqp_MonitorType"                           , null                                             },
                { "'' as Eqp_MonitorStatus"                           , null                                             },
                { "'' as Prev_Eqp_MonitorStatus"                           , null                                             },
                { BizConstant.SP_HASHDATA_EQPMONJOB_ID +" as Eqp_MonitorJobID"     , BizConstant.SP_HISTORYCOLUMNNAME_EQPMONJOBID                 },
                { BizConstant.SP_HASHDATA_MONJOB_STATUS +" as Eqp_MonitorJobStatus"     , BizConstant.SP_HISTORYCOLUMNNAME_MONJOBSTATUS                },
                { BizConstant.SP_HASHDATA_PREV_MONJOB_STATUS +" as Prev_Eqp_MonitorJobStatus", BizConstant.SP_HISTORYCOLUMNNAME_PREVMONJOBSTATUS            },
                { BizConstant.SP_HASHDATA_RETRY_COUNT +" as RetryCount"       , BizConstant.SP_HISTORYCOLUMNNAME_RETRYCOUNT                  },
                { "'' as BufferRscCategory"                           , null                                             },
                { "0 as SM_Capacity"                            , null                                             },
                { "0 as Dynamic_Capacity"                            , null                                             },
                { "'' as PortType"                           , null                                             },
                { "'' as PortUsage"                           , null                                             },
                { "'' as PortState"                           , null                                             },
                { "'' as DispatchedState"                           , null                                             },
                { "TO_TIMESTAMP('1901-01-01-00.00.00.000000','yyyy-mm-dd hh24:mi:ss.ff') as DispatchedTime" , null                                             },
                { "'' as Dispatched_DulableID"                           , null                                             },
                { "TO_TIMESTAMP('1901-01-01-00.00.00.000000','yyyy-mm-dd hh24:mi:ss.ff') as ClaimedTime" , null                                             },
                { "0 as ClaimedShopDate"                            , null                                             },
                { BizConstant.SP_HASHDATA_CLAIM_USER_ID      , BizConstant.SP_HISTORYCOLUMNNAME_USERID                      },
                { BizConstant.SP_HASHDATA_CLAIM_MEMO       , BizConstant.SP_HISTORYCOLUMNNAME_CLAIMMEMO                   },
                { BizConstant.SP_HASHDATA_STORE_TIME        , BizConstant.SP_HISTORYCOLUMNNAME_STOREDTIMESTAMP             } };

        public static final String[][] selectItemOHSEASONJOB = { { BizConstant.SP_HASHDATA_EVENT_CREATE_TIME   , BizConstant.SP_HISTORYCOLUMNNAME_REPORTTIMESTAMP       },
                { "'OHSEASONJOB' as HistoryName"                    , BizConstant.SP_HISTORYCOLUMNNAME_HISTORYNAME           },
                { "'' as PortID"                           , null                                             },
                { BizConstant.SP_HASHDATA_CHAMBER +" as ChamberID"        , BizConstant.SP_HISTORYCOLUMNNAME_CHAMBERID                   },
                { BizConstant.SP_HASHDATA_OPE_CATEGORY +" as OperationCategory"     , BizConstant.SP_HISTORYCOLUMNNAME_OPERATIONCATEGORY           },
                { "'' as OperationMode"                           , null                                             },
                { "'' as LogicalRecipeID"                           , null                                             },
                { "'' as MachineRecipeID"                           , null                                             },
                { "'' as PhysicalRecipeID"                           , null                                             },
                { "'' as ControlJobID"                           , null                                             },
                { "'' as E10Status"                           , null                                             },
                { "'' as EquipmentStatus"                           , null                                             },
                { "'' as ChamberStatus"                           , null                                             },
                { "'' as New_E10Status"                           , null                                             },
                { "'' as New_EquipmentStatus"                           , null                                             },
                { "'' as New_ChamberStatus"                           , null                                             },
                { "'' as TCS_Report_E10Status"                           , null                                             },
                { "'' as TCS_Report_EquipmentStatus"                           , null                                             },
                { "'' as TCS_Report_ChamberStatus"                           , null                                             },
                { "'' as TCS_Report_New_E10Status"                           , null                                             },
                { "'' as TCS_Report_New_EquipmentStatus"                           , null                                             },
                { "'' as TCS_Report_New_ChamberStatus"                           , null                                             },
                { "'' as Equipment_OperationMode"                           , null                                             },
                { "'' as New_Equipment_OperationMode"                           , null                                             },
                { "TO_TIMESTAMP('1901-01-01-00.00.00.000000','yyyy-mm-dd hh24:mi:ss.ff') as Status_Mode_StartedTime" , null                                             },
                { "0 as Status_Mode_Started_ShopDate"                            , null                                             },
                { "TO_TIMESTAMP('1901-01-01-00.00.00.000000','yyyy-mm-dd hh24:mi:ss.ff') as Status_Mode_EndedTime" , null                                             },
                { "0 as Status_Mode_EndedShopDate"                            , null                                             },
                { "'' as Port_OperationMode"                           , null                                             },
                { "'' as Port_OnlineMode"                           , null                                             },
                { "'' as Port_DispatchMode"                           , null                                             },
                { "'' as Port_AccessMode"                           , null                                             },
                { "'' as Port_Operation_StartMode"                           , null                                             },
                { "'' as Port_Operation_CompletionMode"                           , null                                             },
                { "'' as Description_of_OperationMode"                           , null                                             },
                { BizConstant.SP_HASHDATA_SEASON_ID + " as Eqp_SeasonID"         , BizConstant.SP_HISTORYCOLUMNNAME_SEASONID                    },
                { "'' as Eqp_MonitorType"                           , null                                             },
                { "'' as Eqp_MonitorStatus"                           , null                                             },
                { "'' as Prev_Eqp_MonitorStatus"                           , null                                             },
                { BizConstant.SP_HASHDATA_SEASON_JOB_ID +" as Eqp_SeasonJobID"     , BizConstant.SP_HISTORYCOLUMNNAME_SEASONJOBID                 },
                { BizConstant.SP_HASHDATA_SEASON_JOB_STATUS +" as Eqp_MonitorJobStatus"     , BizConstant.SP_HISTORYCOLUMNNAME_SEASONJOBSTATUS                },
                { "'' as Prev_Eqp_MonitorJobStatus", null            },
                { "0 as RetryCount"       , null                  },
                { "'' as BufferRscCategory"                           , null                                             },
                { "0 as SM_Capacity"                            , null                                             },
                { "0 as Dynamic_Capacity"                            , null                                             },
                { "'' as PortType"                           , null                                             },
                { "'' as PortUsage"                           , null                                             },
                { "'' as PortState"                           , null                                             },
                { "'' as DispatchedState"                           , null                                             },
                { "TO_TIMESTAMP('1901-01-01-00.00.00.000000','yyyy-mm-dd hh24:mi:ss.ff') as DispatchedTime" , null                                             },
                { "'' as Dispatched_DulableID"                           , null                                             },
                { "TO_TIMESTAMP('1901-01-01-00.00.00.000000','yyyy-mm-dd hh24:mi:ss.ff') as ClaimedTime" , null                                             },
                { "0 as ClaimedShopDate"                            , null                                             },
                { BizConstant.SP_HASHDATA_CLAIM_USER_ID      , BizConstant.SP_HISTORYCOLUMNNAME_USERID                      },
                { BizConstant.SP_HASHDATA_CLAIM_MEMO       , BizConstant.SP_HISTORYCOLUMNNAME_CLAIMMEMO                   },
                { "TO_TIMESTAMP('1901-01-01-00.00.00.000000','yyyy-mm-dd hh24:mi:ss.ff') as StoreTime"         , null            } };

        public static final String[][] selectItemFHBUFFRSCCHS = { { BizConstant.SP_HASHDATA_EVENT_CREATE_TIME  , BizConstant.SP_HISTORYCOLUMNNAME_REPORTTIMESTAMP  },
                { "'OHEQBUFCHG' as HistoryName"               , BizConstant.SP_HISTORYCOLUMNNAME_HISTORYNAME                 },
                { "'' as PortID"                           , null                                             },
                { "'' as ChamberID"                           , null                                             },
                { "'' as OperationCategory"                           , null                                             },
                { "'' as OperationMode"                           , null                                             },
                { "'' as LogicalRecipeID"                           , null                                             },
                { "'' as MachineRecipeID"                           , null                                             },
                { "'' as PhysicalRecipeID"                           , null                                             },
                { "'' as ControlJobID"                           , null                                             },
                { BizConstant.SP_HASHDATA_E10_STATE + " as E10Status"         , BizConstant.SP_HISTORYCOLUMNNAME_E10STATUS                   },
                { BizConstant.SP_HASHDATA_EQP_STATE + " as EquipmentStatus"          , BizConstant.SP_HISTORYCOLUMNNAME_EQUIPMENTSTATUS             },
                { "'' as ChamberStatus"                           , null                                             },
                { "'' as New_E10Status"                           , null                                             },
                { "'' as New_EquipmentStatus"                           , null                                             },
                { "'' as New_ChamberStatus"                           , null                                             },
                { "'' as TCS_Report_E10Status"                           , null                                             },
                { "'' as TCS_Report_EquipmentStatus"                           , null                                             },
                { "'' as TCS_Report_ChamberStatus"                           , null                                             },
                { "'' as TCS_Report_New_E10Status"                           , null                                             },
                { "'' as TCS_Report_New_EquipmentStatus"                           , null                                             },
                { "'' as TCS_Report_New_ChamberStatus"                           , null                                             },
                { "'' as Equipment_OperationMode"                           , null                                             },
                { "'' as New_Equipment_OperationMode"                           , null                                             },
                { "TO_TIMESTAMP('1901-01-01-00.00.00.000000','yyyy-mm-dd hh24:mi:ss.ff') as Status_Mode_StartedTime" , null                                             },
                { "0 as Status_Mode_Started_ShopDate"                            , null                                             },
                { "TO_TIMESTAMP('1901-01-01-00.00.00.000000','yyyy-mm-dd hh24:mi:ss.ff') as Status_Mode_EndedTime" , null                                             },
                { "0 as Status_Mode_EndedShopDate"                            , null                                             },
                { "'' as Port_OperationMode"                           , null                                             },
                { "'' as Port_OnlineMode"                           , null                                             },
                { "'' as Port_DispatchMode"                           , null                                             },
                { "'' as Port_AccessMode"                           , null                                             },
                { "'' as Port_Operation_StartMode"                           , null                                             },
                { "'' as Port_Operation_CompletionMode"                           , null                                             },
                { "'' as Description_of_OperationMode"                           , null                                             },
                { "'' as Eqp_MonitorID"                           , null                                             },
                { "'' as Eqp_MonitorType"                           , null                                             },
                { "'' as Eqp_MonitorStatus"                           , null                                             },
                { "'' as Prev_Eqp_MonitorStatus"                           , null                                             },
                { "'' as Eqp_MonitorJobID"                           , null                                             },
                { "'' as Eqp_MonitorJobStatus"                           , null                                             },
                { "'' as Prev_Eqp_MonitorJobStatus"                           , null                                             },
                { "0 as RetryCount"                            , null                                             },
                { BizConstant.SP_HASHDATA_BUFFRSC_CATEGORY + " as BufferRscCategory"  , BizConstant.SP_HISTORYCOLUMNNAME_BUFFRSCCATEGORY             },
                { BizConstant.SP_HASHDATA_SM_CAPACITY + " as SM_Capacity"       , BizConstant.SP_HISTORYCOLUMNNAME_SMCAPACITY                  },
                { BizConstant.SP_HASHDATA_DYNAMIC_CAPACITY + " as Dynamic_Capacity"  , BizConstant.SP_HISTORYCOLUMNNAME_DYNAMICCAPACITY             },
                { "'' as PortType"                           , null                                             },
                { "'' as PortUsage"                           , null                                             },
                { "'' as PortState"                           , null                                             },
                { "'' as DispatchedState"                           , null                                             },
                { "TO_TIMESTAMP('1901-01-01-00.00.00.000000','yyyy-mm-dd hh24:mi:ss.ff') as DispatchedTime" , null                                             },
                { "'' as Dispatched_DulableID"                           , null                                             },
                { BizConstant.SP_HASHDATA_CLAIM_TIME + " as ClaimedTime"        , BizConstant.SP_HISTORYCOLUMNNAME_CLAIMEDTIME                 },
                { "0 as ClaimedShopDate"                            , null                                             },
                { BizConstant.SP_HASHDATA_CLAIM_USER_ID      , BizConstant.SP_HISTORYCOLUMNNAME_USERID                      },
                { BizConstant.SP_HASHDATA_CLAIM_MEMO         , BizConstant.SP_HISTORYCOLUMNNAME_CLAIMMEMO                   },
                { BizConstant.SP_HASHDATA_STORE_TIME         , BizConstant.SP_HISTORYCOLUMNNAME_STOREDTIMESTAMP             }
        };

        public static final String[][] selectItemFHEQPPORTSCHS = { { BizConstant.SP_HASHDATA_EVENT_CREATE_TIME  , BizConstant.SP_HISTORYCOLUMNNAME_REPORTTIMESTAMP  },
                { "'OHEQPRTSC' as HistoryName"              , BizConstant.SP_HISTORYCOLUMNNAME_HISTORYNAME                 },
                { BizConstant.SP_HASHDATA_PORT_ID + " as PortID"           , BizConstant.SP_HISTORYCOLUMNNAME_PORTID                      },
                { "'' as ChamberID"                           , null                                             },
                { "'' as OperationCategory"                           , null                                             },
                { "'' as OperationMode"                           , null                                             },
                { "'' as LogicalRecipeID"                           , null                                             },
                { "'' as MachineRecipeID"                           , null                                             },
                { "'' as PhysicalRecipeID"                           , null                                             },
                { "'' as ControlJobID"                           , null                                             },
                { "'' as E10Status"                           , null                                             },
                { "'' as EquipmentStatus"                           , null                                             },
                { "'' as ChamberStatus"                           , null                                             },
                { "'' as New_E10Status"                           , null                                             },
                { "'' as New_EquipmentStatus"                           , null                                             },
                { "'' as New_ChamberStatus"                           , null                                             },
                { "'' as TCS_Report_E10Status"                           , null                                             },
                { "'' as TCS_Report_EquipmentStatus"                           , null                                             },
                { "'' as TCS_Report_ChamberStatus"                           , null                                             },
                { "'' as TCS_Report_New_E10Status"                           , null                                             },
                { "'' as TCS_Report_New_EquipmentStatus"                           , null                                             },
                { "'' as TCS_Report_New_ChamberStatus"                           , null                                             },
                { "'' as Equipment_OperationMode"                           , null                                             },
                { "'' as New_Equipment_OperationMode"                           , null                                             },
                { "TO_TIMESTAMP('1901-01-01-00.00.00.000000','yyyy-mm-dd hh24:mi:ss.ff') as Status_Mode_StartedTime" , null                                             },
                { "0 as Status_Mode_Started_ShopDate"                            , null                                             },
                { "TO_TIMESTAMP('1901-01-01-00.00.00.000000','yyyy-mm-dd hh24:mi:ss.ff') as Status_Mode_EndedTime" , null                                             },
                { "0 as Status_Mode_EndedShopDate"                            , null                                             },
                { "'' as Port_OperationMode"                           , null                                             },
                { "'' as Port_OnlineMode"                           , null                                             },
                { "'' as Port_DispatchMode"                           , null                                             },
                { BizConstant.SP_HASHDATA_ACCESS_MODE + " as Port_AccessMode"       , BizConstant.SP_HISTORYCOLUMNNAME_PORTACCESSMODE              },
                { "'' as Port_Operation_StartMode"                           , null                                             },
                { "'' as Port_Operation_CompletionMode"                           , null                                             },
                { "'' as Description_of_OperationMode"                           , null                                             },
                { "'' as Eqp_MonitorID"                           , null                                             },
                { "'' as Eqp_MonitorType"                           , null                                             },
                { "'' as Eqp_MonitorStatus"                           , null                                             },
                { "'' as Prev_Eqp_MonitorStatus"                           , null                                             },
                { "'' as Eqp_MonitorJobID"                           , null                                             },
                { "'' as Eqp_MonitorJobStatus"                           , null                                             },
                { "'' as Prev_Eqp_MonitorJobStatus"                           , null                                             },
                { "0 as RetryCount"                          , null                                             },
                { "'' as BufferRscCategory"                           , null                                             },
                { "0 as SM_Capacity"                            , null                                             },
                { "0 as Dynamic_Capacity"                            , null                                             },
                { BizConstant.SP_HASHDATA_PORT_TYPE + " as PortType"         , BizConstant.SP_HISTORYCOLUMNNAME_PORTTYPE                    },
                { BizConstant.SP_HASHDATA_PORT_USAGE + " as PortUsage"        , BizConstant.SP_HISTORYCOLUMNNAME_PORTUSAGE                   },
                { BizConstant.SP_HASHDATA_PORT_STATE + " as PortState"        , BizConstant.SP_HISTORYCOLUMNNAME_PORTSTATE                   },
                { BizConstant.SP_HASHDATA_DISP_STATE + " as DispatchedState"        , BizConstant.SP_HISTORYCOLUMNNAME_DISPATCHSTATE               },
                { BizConstant.SP_HASHDATA_DISP_TIME + " as DispatchedTime"          , BizConstant.SP_HISTORYCOLUMNNAME_DISPATCHTIME                },
                { BizConstant.SP_HASHDATA_DISP_DRBL_ID + " as Dispatched_DulableID"      , BizConstant.SP_HISTORYCOLUMNNAME_DISPATCHDURABLEID           },
                { BizConstant.SP_HASHDATA_CLAIM_TIME + " as ClaimedTime"        , BizConstant.SP_HISTORYCOLUMNNAME_CLAIMEDTIME                 },
                { "0 as ClaimedShopDate"                            , null                                             },
                { BizConstant.SP_HASHDATA_CLAIM_USER_ID      , BizConstant.SP_HISTORYCOLUMNNAME_USERID                      },
                { BizConstant.SP_HASHDATA_CLAIM_MEMO         , BizConstant.SP_HISTORYCOLUMNNAME_CLAIMMEMO                   },
                { BizConstant.SP_HASHDATA_STORE_TIME         , BizConstant.SP_HISTORYCOLUMNNAME_STOREDTIMESTAMP             }
        };
    }


    //-----------------------------------durable-------------------------------------------------//
    public static class DurableConstant {
        public static final String MANDATORY_HASH_KEY = BizConstant.SP_HISTORYCOLUMNNAME_DURABLEID;

        public static final String[][] paramKeyFHDRCHS = { { MANDATORY_HASH_KEY             , BizConstant.SP_HASHDATA_DURABLE_ID    },
                { null                      , null                      } };

        public static final String[][] paramKeyFHDRBLOPEHS = { { MANDATORY_HASH_KEY         , BizConstant.SP_HASHDATA_DURABLE_ID    },
                { null                      , null                      } };

        public static final String[][] paramKeyFHDRJOBSTCHS = { { MANDATORY_HASH_KEY         , BizConstant.SP_HASHDATA_DURABLE_ID    },
                { null                      , null                      } };


        //public static final int SELECT_ITEM_MAX = 19;
        public static final int SELECT_ITEM_MAX = 27;
        public static final String[][] selectItemFHDRCHS = { { BizConstant.SP_HASHDATA_EVENT_CREATE_TIME  , BizConstant.SP_HISTORYCOLUMNNAME_REPORTTIMESTAMP             },
                { "'OHDURSC' HistoryName"                    , BizConstant.SP_HISTORYCOLUMNNAME_HISTORYNAME                 },
                { BizConstant.SP_HASHDATA_DURABLE_TYPE + " DurableType"      , BizConstant.SP_HISTORYCOLUMNNAME_DURABLETYPE                 },
                { "'' OperationCategory"                           , null                                             },
                { "'' OperationMode"                           , null                                             },
                { "'' MachineRecipeID"                           , null                                             },
                { "'' PhysicalRecipeID"                           , null                                             },
                { "'' DurableControlJobID"                           , null                                             },
                { BizConstant.SP_HASHDATA_ACTION_CODE + " ActionCode"       , BizConstant.SP_HISTORYCOLUMNNAME_ACTIONCODE                  },
                { BizConstant.SP_HASHDATA_DURABLE_STATUS + " DurableStatus"    , BizConstant.SP_HISTORYCOLUMNNAME_DURABLESTATUS               },
                { BizConstant.SP_HASHDATA_DRBLSUBSTATE_ID + " DurableSubStatus"   , BizConstant.SP_HISTORYCOLUMNNAME_DURABLESUBSTATUS            },
                { BizConstant.SP_HASHDATA_XFER_STATUS + " XferStatus"       , BizConstant.SP_HISTORYCOLUMNNAME_XFERSTATUS                  },
                { BizConstant.SP_HASHDATA_XFER_STAT_CHG_TIME  + " XferStatusChangeTime" , BizConstant.SP_HISTORYCOLUMNNAME_XFERSTATUSCHANGETIME        },
                { BizConstant.SP_HASHDATA_LOCATION + " Location"          , BizConstant.SP_HISTORYCOLUMNNAME_LOCATION                    },
                { BizConstant.SP_HASHDATA_CLAIM_TIME + " ClaimedTime"        , BizConstant.SP_HISTORYCOLUMNNAME_CLAIMEDTIME                 },
                { BizConstant.SP_HASHDATA_CLAIM_SHOP_DATE + " ClaimedShopDate"   , BizConstant.SP_HISTORYCOLUMNNAME_CLAIMEDSHOPDATE             },

                // job status history column start
                { "'' JobStatus"    , null              },
                { "TO_TIMESTAMP('1901-01-01-00.00.00.000000','yyyy-MM-dd-HH24.mi.SSxFF') JobStatusChangeTime"    , null               },
                { "'' Process"    , null               },
                { "'' Route"    , null               },
                { "'' Step"    , null               },
                { "'' OperationNo"    , null               },
                { "'' Equipment"    , null               },
                { "'' Chamber"    , null               },
                // job status history column end

                { BizConstant.SP_HASHDATA_CLAIM_USER_ID     , BizConstant.SP_HISTORYCOLUMNNAME_USERID                      },
                { BizConstant.SP_HASHDATA_CLAIM_MEMO         , BizConstant.SP_HISTORYCOLUMNNAME_CLAIMMEMO                   },
                { BizConstant.SP_HASHDATA_STORE_TIME         , BizConstant.SP_HISTORYCOLUMNNAME_STOREDTIMESTAMP             }
        };
        public static final String[][] selectItemFHDRBLOPEHS = { { BizConstant.SP_HASHDATA_EVENT_CREATE_TIME  , BizConstant.SP_HISTORYCOLUMNNAME_REPORTTIMESTAMP             },
                { "'OHDUROPE' HistoryName"                , BizConstant.SP_HISTORYCOLUMNNAME_HISTORYNAME                 },
                { BizConstant.SP_HASHDATA_DRBL_CATEGORY + " DurableType"     , BizConstant.SP_HISTORYCOLUMNNAME_DURABLETYPE                 },
                { BizConstant.SP_HASHDATA_OPE_CATEGORY + " OperationCategory"      , BizConstant.SP_HISTORYCOLUMNNAME_OPERATIONCATEGORY           },
                { BizConstant.SP_HASHDATA_OPE_MODE  + " OperationMode"         , BizConstant.SP_HISTORYCOLUMNNAME_OPERATIONMODE               },
                { BizConstant.SP_HASHDATA_RECIPE_ID + " MachineRecipeID"         , BizConstant.SP_HISTORYCOLUMNNAME_MACHINERECIPEID             },
                { BizConstant.SP_HASHDATA_PH_RECIPE_ID + " PhysicalRecipeID"      , BizConstant.SP_HISTORYCOLUMNNAME_PHYSICALRECIPEID            },
                { BizConstant.SP_HASHDATA_DCTRL_JOB + " DurableControlJobID"         , BizConstant.SP_HISTORYCOLUMNNAME_DURABLECONTROLJOBID         },
                { "'' ActionCode"                           , null                                             },
                { "'' DurableStatus"                           , null                                             },
                { "'' DurableSubStatus"                           , null                                             },
                { "'' XferStatus"                           , null                                             },
                { "TO_TIMESTAMP('1901-01-01-00.00.00.000000','yyyy-MM-dd-HH24.mi.SSxFF') XferStatusChangeTime" , null                                             },
                { "'' Location"                           , null                                             },
                { "TO_TIMESTAMP('1901-01-01-00.00.00.000000','yyyy-MM-dd-HH24.mi.SSxFF') ClaimedTime" , null                                             },
                { "0 ClaimedShopDate"                            , null                                             },

                // job status history column start
                { "'' JobStatus"    , null              },
                { "TO_TIMESTAMP('1901-01-01-00.00.00.000000','yyyy-MM-dd-HH24.mi.SSxFF') JobStatusChangeTime"    , null               },
                { "'' Process"    , null               },
                { "'' Route"    , null               },
                { "'' Step"    , null               },
                { "'' OperationNo"    , null               },
                { "'' Equipment"    , null               },
                { "'' Chamber"    , null               },
                // job status history column end

                { BizConstant.SP_HASHDATA_CLAIM_USER_ID      , BizConstant.SP_HISTORYCOLUMNNAME_USERID                      },
                { BizConstant.SP_HASHDATA_CLAIM_MEMO         , BizConstant.SP_HISTORYCOLUMNNAME_CLAIMMEMO                   },
                { BizConstant.SP_HASHDATA_STORE_TIME         , BizConstant.SP_HISTORYCOLUMNNAME_STOREDTIMESTAMP             }
        };
        public static final String[][] selectItemFHDRJOBSTCHS = {
                { BizConstant.SP_HASHDATA_EVENT_CREATE_TIME  , BizConstant.SP_HISTORYCOLUMNNAME_REPORTTIMESTAMP             },
                { "'OHDRJOBSTCHS' HistoryName"                    , BizConstant.SP_HISTORYCOLUMNNAME_HISTORYNAME                 },
                { BizConstant.SP_HASHDATA_DURABLE_TYPE + " DurableType"      , BizConstant.SP_HISTORYCOLUMNNAME_DURABLETYPE                 },
                { "'' OperationCategory"                           , null                                             },
                { "'' OperationMode"                           , null                                             },
                { "'' MachineRecipeID"                           , null                                             },
                { "'' PhysicalRecipeID"                           , null                                             },
                { "'' DurableControlJobID"                           , null                                             },
                { BizConstant.SP_HASHDATA_ACTION_CODE + " ActionCode"       , BizConstant.SP_HISTORYCOLUMNNAME_ACTIONCODE                  },
                { "'' DurableStatus"    , null               },
                { "'' DurableSubStatus"   , null            },
                { "'' XferStatus"       , null                  },
                { "TO_TIMESTAMP('1901-01-01-00.00.00.000000','yyyy-MM-dd-HH24.mi.SSxFF') XferStatusChangeTime" , null        },
                { "'' Location"          , null                    },
                { "TO_TIMESTAMP('1901-01-01-00.00.00.000000','yyyy-MM-dd-HH24.mi.SSxFF') ClaimedTime"        , null                 },
                { "0 ClaimedShopDate"   , null             },

                // job status history column start
                { BizConstant.SP_HASHDATA_DURABLE_JOB_STATUS + " JobStatus"    , BizConstant.SP_HISTORYCOLUMNNAME_DURABLE_JOB_STATUS               },
                { BizConstant.SP_HASHDATA_DURABLE_JOB_STATUS_CHANGE_TIME + " JobStatusChangeTime"    , BizConstant.SP_HISTORYCOLUMNNAME_DURABLE_JOB_STATUS_CHANGE_TIME               },
                { BizConstant.SP_HASHDATA_DURABLE_JOB_STATUS_PROCESS + " Process"    , BizConstant.SP_HISTORYCOLUMNNAME_DURABLE_JOB_STATUS_PROCESS               },
                { BizConstant.SP_HASHDATA_DURABLE_JOB_STATUS_ROUTE + " Route"    , BizConstant.SP_HISTORYCOLUMNNAME_DURABLE_JOB_STATUS_ROUTE               },
                { BizConstant.SP_HASHDATA_DURABLE_JOB_STATUS_STEP + " Step"    , BizConstant.SP_HISTORYCOLUMNNAME_DURABLE_JOB_STATUS_STEP               },
                { BizConstant.SP_HASHDATA_DURABLE_JOB_STATUS_OPE_NO + " OperationNo"    , BizConstant.SP_HISTORYCOLUMNNAME_DURABLE_JOB_STATUS_OPE_NO               },
                { BizConstant.SP_HASHDATA_DURABLE_JOB_STATUS_EQP_ID + " Equipment"    , BizConstant.SP_HISTORYCOLUMNNAME_DURABLE_JOB_STATUS_EQP               },
                { BizConstant.SP_HASHDATA_DURABLE_JOB_STATUS_CHAMBER_ID + " Chamber"    , BizConstant.SP_HISTORYCOLUMNNAME_DURABLE_JOB_STATUS_CHAMBER               },
                // job status history column end

                { BizConstant.SP_HASHDATA_CLAIM_USER_ID     , BizConstant.SP_HISTORYCOLUMNNAME_USERID                      },
                { BizConstant.SP_HASHDATA_CLAIM_MEMO         , BizConstant.SP_HISTORYCOLUMNNAME_CLAIMMEMO                   },
                { BizConstant.SP_HASHDATA_STORE_TIME         , BizConstant.SP_HISTORYCOLUMNNAME_STOREDTIMESTAMP             }
        };
    }

    //reticle
    public static class ReticleConstant {
        public static final String[] MANDATORY_HASH_KEY = {BizConstant.SP_HISTORYCOLUMNNAME_RETICLEID, BizConstant.SP_HISTORYCOLUMNNAME_DURABLEID};

        public static final String[][] paramKeyOHRTLHS = { { MANDATORY_HASH_KEY[0]         , BizConstant.SP_HASHDATA_RETICLE_ID    },
                { null                      , null                      } };

        public static final String[][] paramKeyFHDRCHS = { { MANDATORY_HASH_KEY[1]        , BizConstant.SP_HASHDATA_DURABLE_ID    },
                { null                      , null                      } };


        public static final int SELECT_ITEM_MAX = 17;

        public static final String[][] selectItemFHDRCHS = {
                { BizConstant.SP_HASHDATA_CLAIM_TIME  , BizConstant.SP_HISTORYCOLUMNNAME_CLAIMEDTIME             },
                { "'OHDURSC' HistoryName"                    , BizConstant.SP_HISTORYCOLUMNNAME_HISTORYNAME                 },
                { "'' ReticleType"       , null                 },
                { "'' OperationCategory"       , null                 },
                { BizConstant.SP_HASHDATA_DURABLE_STATUS + " ReticleStatus"    , "Reticle Status"               },
                { "'' InspectionType"       , null                  },
                { BizConstant.SP_HASHDATA_DRBLSUBSTATE_ID + " ReticleSubStatus"   , "Reticle Sub Status"            },
                { "'' ReticleGrade"       , null                  },
                { "'' ReticleLocation"       , null                 },
                { "'' ReticlePodID"   ,  null           },
                { "'' EqpID"          , null                   },
                { "'' StockerID"        , null                },
                { "'' ReasonCode"   , null             },
                { "'' TransactionID"   ,  null          },
                { BizConstant.SP_HASHDATA_XFER_STATUS + " XferStatus"   , BizConstant.SP_HISTORYCOLUMNNAME_XFERSTATUS     },
                { BizConstant.SP_HASHDATA_CLAIM_MEMO         , BizConstant.SP_HISTORYCOLUMNNAME_CLAIMMEMO                   },
                { BizConstant.SP_HASHDATA_CLAIM_USER_ID     , BizConstant.SP_HISTORYCOLUMNNAME_USERID                      },
        };
        public static final String[][] selectItemOHRTLHS = {
                {  BizConstant.SP_HASHDATA_CLAIM_TIME  + " ClaimTime", BizConstant.SP_HISTORYCOLUMNNAME_CLAIMEDTIME             },
                { "'OHRTLHS' HistoryName"                    , BizConstant.SP_HISTORYCOLUMNNAME_HISTORYNAME                 },
                { BizConstant.SP_HASHDATA_RETICLE_TYPE + " ReticleType"       , BizConstant.SP_HISTORYCOLUMNNAME_RETICLETYPE                  },
                { BizConstant.SP_HASHDATA_OPE_CATEGORY + " OperationCategory"       , BizConstant.SP_HISTORYCOLUMNNAME_OPERATIONCATEGORY                  },
                { BizConstant.SP_HASHDATA_INSPECTION_TYPE + " InspectionType"       , "Inspection Type"                  },
                { BizConstant.SP_HASHDATA_XFER_STATUS + " XferStatus"   , BizConstant.SP_HISTORYCOLUMNNAME_XFERSTATUS     },
                { BizConstant.SP_HASHDATA_RETICLE_STATUS + " ReticleStatus"    , "Reticle Status"               },
                { BizConstant.SP_HASHDATA_RETICLE_SUB_STATUS + " ReticleSubStatus"   , "Reticle Sub Status"            },
                { BizConstant.SP_HASHDATA_RETICLE_GRADE + " ReticleGrade"       , "Reticle Grade"                  },
                { BizConstant.SP_HASHDATA_RETICLE_LOCATION + " ReticleLocation"       , "Reticle Location"                 },
                { BizConstant.SP_HASHDATA_RETICLE_POD_ID + " ReticlePodID"   , "Reticle Pod ID"            },
                { BizConstant.SP_HASHDATA_EQP_ID + " EqpID"          , "Eqp ID"                    },
                { BizConstant.SP_HASHDATA_STOCKER_ID + " StockerID"        , "Stocker ID"                 },
                { BizConstant.SP_HASHDATA_REASON_CODE + " ReasonCode"   , "Reason Code"             },
                { BizConstant.SP_HASHDATA_TRANSACTION_ID + " TransactionID"   , "Transaction ID"          },
                { BizConstant.SP_HASHDATA_CLAIM_MEMO         + " ClaimMemo", BizConstant.SP_HISTORYCOLUMNNAME_CLAIMMEMO                   },
                { BizConstant.SP_HASHDATA_CLAIM_USER_ID         + " ClaimUser", BizConstant.SP_HISTORYCOLUMNNAME_USERID                },
        };
    }
}